import Letter from './models/letter.model';

const HIRAGANA: Letter[] = [
  { record: 'ka', sign: 'か' },
  { record: 'ki', sign: 'き' },
  { record: 'ku', sign: 'く' },
  { record: 'ke', sign: 'け' },
  { record: 'ko', sign: 'こ' },
  { record: 'kya', sign: 'きゃ' },
  { record: 'kyu', sign: 'きゅ' },
  { record: 'kyo', sign: 'きょ' },
  { record: 'ga', sign: 'が' },
  { record: 'gi', sign: 'ぎ' },
  { record: 'gu', sign: 'ぐ' },
  { record: 'ge', sign: 'げ' },
  { record: 'go', sign: 'ご' },
  { record: 'gya', sign: 'ぎゃ' },
  { record: 'gyu', sign: 'ぎゅ' },
  { record: 'gyo', sign: 'ぎょ' },

  { record: 'ta', sign: 'た' },
  { record: 'chi', sign: 'ち' },
  { record: 'tsu', sign: 'つ' },
  { record: 'te', sign: 'て' },
  { record: 'to', sign: 'と' },
  { record: 'cha', sign: 'ちゃ' },
  { record: 'chu', sign: 'ちゅ' },
  { record: 'cho', sign: 'ちょ' },
  { record: 'da', sign: 'だ' },
  { record: 'dji', sign: 'ぢ' },
  { record: 'dzu', sign: 'づ' },
  { record: 'de', sign: 'で' },
  { record: 'do', sign: 'ど' },
  { record: 'dya', sign: 'ぢゃ' },
  { record: 'dyu', sign: 'ぢゅ' },
  { record: 'dyo', sign: 'ぢょ' },

  { record: 'sa', sign: 'さ' },
  { record: 'shi', sign: 'し' },
  { record: 'su', sign: 'す' },
  { record: 'se', sign: 'せ' },
  { record: 'so', sign: 'そ' },
  { record: 'sha', sign: 'しゃ' },
  { record: 'shu', sign: 'しゅ' },
  { record: 'sho', sign: 'しょ' },
  { record: 'za', sign: 'ざ' },
  { record: 'ji', sign: 'じ' },
  { record: 'zu', sign: 'ず' },
  { record: 'ze', sign: 'ぜ' },
  { record: 'zo', sign: 'ぞ' },
  { record: 'jya', sign: 'じゃ' },
  { record: 'jyu', sign: 'じゅ' },
  { record: 'jyo', sign: 'じょ' },

  { record: 'na', sign: 'な' },
  { record: 'ni', sign: 'に' },
  { record: 'nu', sign: 'ぬ' },
  { record: 'ne', sign: 'ね' },
  { record: 'no', sign: 'の' },
  { record: 'nya', sign: 'にゃ' },
  { record: 'nyu', sign: 'にゅ' },
  { record: 'nyo', sign: 'にょ' },

  { record: 'ha', sign: 'は' },
  { record: 'hi', sign: 'ひ' },
  { record: 'fu', sign: 'ふ' },
  { record: 'he', sign: 'へ' },
  { record: 'ho', sign: 'ほ' },
  { record: 'hya', sign: 'ひゃ' },
  { record: 'hyu', sign: 'ひゅ' },
  { record: 'hyo', sign: 'ひょ' },
  { record: 'ba', sign: 'ば' },
  { record: 'bi', sign: 'び' },
  { record: 'bu', sign: 'ぶ' },
  { record: 'be', sign: 'べ' },
  { record: 'bo', sign: 'ぼ' },
  { record: 'bya', sign: 'びゃ' },
  { record: 'byu', sign: 'びゅ' },
  { record: 'byo', sign: 'びょ' },
  { record: 'pa', sign: 'ぱ' },
  { record: 'pi', sign: 'ぴ' },
  { record: 'pu', sign: 'ぷ' },
  { record: 'pe', sign: 'ぺ' },
  { record: 'po', sign: 'ぽ' },
  { record: 'pya', sign: 'ぴゃ' },
  { record: 'pyu', sign: 'ぴゅ' },
  { record: 'pyo', sign: 'ぴょ' },

  { record: 'ma', sign: 'ま' },
  { record: 'mi', sign: 'み' },
  { record: 'mu', sign: 'む' },
  { record: 'me', sign: 'め' },
  { record: 'mo', sign: 'も' },
  { record: 'mya', sign: 'みゃ' },
  { record: 'myu', sign: 'みゅ' },
  { record: 'myo', sign: 'みょ' },

  { record: 'ra', sign: 'ら' },
  { record: 'ri', sign: 'り' },
  { record: 'ru', sign: 'る' },
  { record: 're', sign: 'れ' },
  { record: 'ro', sign: 'ろ' },
  { record: 'rya', sign: 'りゃ' },
  { record: 'ryu', sign: 'りゅ' },
  { record: 'ryo', sign: 'りょ' },

  { record: 'ya', sign: 'や' },
  { record: 'yu', sign: 'ゆ' },
  { record: 'yo', sign: 'よ' },

  { record: 'wa', sign: 'わ' },
  { record: 'wi', sign: 'ゐ' },
  { record: 'we', sign: 'ゑ' },
  { record: 'wo', sign: 'を' },

  { record: 'a', sign: 'あ' },
  { record: 'i', sign: 'い' },
  { record: 'u', sign: 'う' },
  { record: 'e', sign: 'え' },
  { record: 'o', sign: 'お' },

  { record: 'nn', sign: 'ん' },
];

export default HIRAGANA;
