import Letter from './models/letter.model';

const KATAKANA: Letter[] = [
  { record: 'KA', sign: 'カ' },
  { record: 'KI', sign: 'キ' },
  { record: 'KU', sign: 'ク' },
  { record: 'KE', sign: 'ケ' },
  { record: 'KO', sign: 'コ' },
  { record: 'KYA', sign: 'キャ' },
  { record: 'KYU', sign: 'キュ' },
  { record: 'KYO', sign: 'キョ' },
  { record: 'GA', sign: 'ガ' },
  { record: 'GI', sign: 'ギ' },
  { record: 'GU', sign: 'グ' },
  { record: 'GE', sign: 'ゲ' },
  { record: 'GO', sign: 'ゴ' },
  { record: 'GYA', sign: 'ギャ' },
  { record: 'GYU', sign: 'ギュ' },
  { record: 'GYO', sign: 'ギョ' },

  { record: 'TA', sign: 'タ' },
  { record: 'CHI', sign: 'チ' },
  { record: 'TSU', sign: 'ツ' },
  { record: 'TE', sign: 'テ' },
  { record: 'TO', sign: 'ト' },
  { record: 'CHA', sign: 'チャ' },
  { record: 'CHU', sign: 'チュ' },
  { record: 'CHO', sign: 'チョ' },
  { record: 'DA', sign: 'ダ' },
  { record: 'DJI', sign: 'ヂ' },
  { record: 'DZU', sign: 'ヅ' },
  { record: 'DE', sign: 'デ' },
  { record: 'DO', sign: 'ド' },
  { record: 'DYA', sign: 'ヂャ' },
  { record: 'DYU', sign: 'ヂュ' },
  { record: 'DYO', sign: 'ヂョ' },

  { record: 'SA', sign: 'サ' },
  { record: 'SHI', sign: 'シ' },
  { record: 'SU', sign: 'ス' },
  { record: 'SE', sign: 'セ' },
  { record: 'SO', sign: 'ソ' },
  { record: 'SHA', sign: 'シャ' },
  { record: 'SHU', sign: 'シュ' },
  { record: 'SHO', sign: 'ショ' },
  { record: 'ZA', sign: 'ザ' },
  { record: 'JI', sign: 'ジ' },
  { record: 'ZU', sign: 'ズ' },
  { record: 'ZE', sign: 'ゼ' },
  { record: 'ZO', sign: 'ゾ' },
  { record: 'JYA', sign: 'ジゃ' },
  { record: 'JYU', sign: 'ジゅ' },
  { record: 'JYO', sign: 'ジょ' },

  { record: 'NA', sign: 'ナ' },
  { record: 'NI', sign: 'ニ' },
  { record: 'NU', sign: 'ヌ' },
  { record: 'NE', sign: 'ネ' },
  { record: 'NO', sign: 'ノ' },
  { record: 'NYA', sign: 'ニャ' },
  { record: 'NYU', sign: 'ニュ' },
  { record: 'NYO', sign: 'ニョ' },

  { record: 'HA', sign: 'ハ' },
  { record: 'HI', sign: 'ヒ' },
  { record: 'FU', sign: 'フ' },
  { record: 'HE', sign: 'ヘ' },
  { record: 'HO', sign: 'ホ' },
  { record: 'HYA', sign: 'ヒャ' },
  { record: 'HYU', sign: 'ヒュ' },
  { record: 'HYO', sign: 'ヒョ' },
  { record: 'BA', sign: 'バ' },
  { record: 'BI', sign: 'ビ' },
  { record: 'BU', sign: 'ブ' },
  { record: 'BE', sign: 'ベ' },
  { record: 'BO', sign: 'ボ' },
  { record: 'BYA', sign: 'ビャ' },
  { record: 'BYU', sign: 'ビュ' },
  { record: 'BYO', sign: 'ビョ' },
  { record: 'PA', sign: 'パ' },
  { record: 'PI', sign: 'ピ' },
  { record: 'PU', sign: 'プ' },
  { record: 'PE', sign: 'ペ' },
  { record: 'PO', sign: 'ポ' },
  { record: 'PYA', sign: 'ピャ' },
  { record: 'PYU', sign: 'ピュ' },
  { record: 'PYO', sign: 'ピョ' },

  { record: 'MA', sign: 'マ' },
  { record: 'MI', sign: 'ミ' },
  { record: 'MU', sign: 'ム' },
  { record: 'ME', sign: 'メ' },
  { record: 'MO', sign: 'モ' },
  { record: 'MYA', sign: 'ミャ' },
  { record: 'MYU', sign: 'ミュ' },
  { record: 'MYO', sign: 'ミョ' },

  { record: 'RA', sign: 'ラ' },
  { record: 'RI', sign: 'リ' },
  { record: 'RU', sign: 'ル' },
  { record: 'RE', sign: 'レ' },
  { record: 'RO', sign: 'ロ' },
  { record: 'RYA', sign: 'リャ' },
  { record: 'RYU', sign: 'リュ' },
  { record: 'RYO', sign: 'リョ' },

  { record: 'YA', sign: 'ヤ' },
  { record: 'YU', sign: 'ユ' },
  { record: 'YO', sign: 'ヨ' },

  { record: 'WA', sign: 'ワ' },
  { record: 'WI', sign: 'ヰ' },
  { record: 'WE', sign: 'ヱ' },
  { record: 'WO', sign: 'ヲ' },

  { record: 'A', sign: 'ア' },
  { record: 'I', sign: 'イ' },
  { record: 'U', sign: 'ウ' },
  { record: 'E', sign: 'エ' },
  { record: 'O', sign: 'オ' },

  { record: 'NN', sign: 'ン' },
];

export default KATAKANA;
