import CharacterType from '../common/enums/character-type.enum';
import Kanji from './models/kanji.model';

const KANJI: Kanji[] = [
  {
    characters: '上',
    meanings: ['above', 'up', 'over'],
    onyomi: ['じょう'],
    kunyomi: ['うえ', 'あ', 'のぼ', 'うわ', 'かみ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '下',
    meanings: ['below', 'down', 'under', 'beneath'],
    onyomi: ['か', 'げ'],
    kunyomi: ['した', 'さ', 'くだ', 'お'],
    type: CharacterType.KANJI,
  },
  {
    characters: '大',
    meanings: ['big', 'large'],
    onyomi: ['たい', 'だい'],
    kunyomi: ['おお'],
    nanori: ['ひろ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '工',
    meanings: ['construction', 'industry', 'artisan', 'work', 'craft'],
    onyomi: ['こう', 'く'],
    type: CharacterType.KANJI,
  },
  {
    characters: '入',
    meanings: ['enter'],
    onyomi: ['にゅう'],
    kunyomi: ['はい', 'い'],
    type: CharacterType.KANJI,
  },
  {
    characters: '山',
    meanings: ['mountain'],
    onyomi: ['さん'],
    kunyomi: ['やま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '口',
    meanings: ['mouth'],
    onyomi: ['こう', 'く'],
    kunyomi: ['くち'],
    type: CharacterType.KANJI,
  },
  {
    characters: '一',
    meanings: ['one'],
    onyomi: ['いち', 'いつ'],
    kunyomi: ['ひと'],
    nanori: ['かず'],
    type: CharacterType.KANJI,
  },
  {
    characters: '二',
    meanings: ['two'],
    onyomi: ['に'],
    kunyomi: ['ふた'],
    type: CharacterType.KANJI,
  },
  {
    characters: '三',
    meanings: ['three'],
    onyomi: ['さん'],
    kunyomi: ['み'],
    type: CharacterType.KANJI,
  },
  {
    characters: '四',
    meanings: ['four'],
    onyomi: ['し'],
    kunyomi: ['よん', 'よ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '五',
    meanings: ['five'],
    onyomi: ['ご'],
    kunyomi: ['いつ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '六',
    meanings: ['six'],
    onyomi: ['ろく'],
    kunyomi: ['む'],
    type: CharacterType.KANJI,
  },
  {
    characters: '七',
    meanings: ['seven'],
    onyomi: ['しち'],
    kunyomi: ['なな', 'なの'],
    type: CharacterType.KANJI,
  },
  {
    characters: '八',
    meanings: ['eight'],
    onyomi: ['はち'],
    kunyomi: ['や', 'よう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '九',
    meanings: ['nine'],
    onyomi: ['く', 'きゅう'],
    kunyomi: ['ここの'],
    type: CharacterType.KANJI,
  },
  {
    characters: '十',
    meanings: ['ten'],
    onyomi: ['じゅう'],
    kunyomi: ['とお'],
    type: CharacterType.KANJI,
  },
  {
    characters: '百',
    meanings: ['hundred'],
    onyomi: ['ひゃく'],
    kunyomi: ['もも'],
    type: CharacterType.KANJI,
  },
  {
    characters: '千',
    meanings: ['thousand'],
    onyomi: ['せん'],
    kunyomi: ['ち'],
    type: CharacterType.KANJI,
  },
  {
    characters: '万',
    meanings: ['ten thousand'],
    onyomi: ['まん', 'ばん'],
    type: CharacterType.KANJI,
  },
  {
    characters: '人',
    meanings: ['person'],
    onyomi: ['にん', 'じん'],
    kunyomi: ['ひと', 'と'],
    type: CharacterType.KANJI,
  },
  {
    characters: '力',
    meanings: ['power', 'strength'],
    onyomi: ['りょく', 'りき'],
    kunyomi: ['ちから'],
    type: CharacterType.KANJI,
  },
  {
    characters: '川',
    meanings: ['river'],
    onyomi: ['せん'],
    kunyomi: ['かわ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '女',
    meanings: ['woman'],
    onyomi: ['じょ'],
    kunyomi: ['おんな', 'め'],
    type: CharacterType.KANJI,
  },
  {
    characters: '又',
    meanings: ['again'],
    kunyomi: ['また'],
    type: CharacterType.KANJI,
  },
  {
    characters: '玉',
    meanings: ['ball'],
    onyomi: ['ぎょく'],
    kunyomi: ['たま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '本',
    meanings: ['book', 'origin', 'real', 'main'],
    onyomi: ['ほん'],
    kunyomi: ['もと'],
    type: CharacterType.KANJI,
  },
  {
    characters: '弓',
    meanings: ['bow'],
    onyomi: ['きゅう'],
    kunyomi: ['ゆみ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '子',
    meanings: ['child', 'kid'],
    onyomi: ['し', 'す'],
    kunyomi: ['こ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '丸',
    meanings: ['circle', 'circular', 'round'],
    onyomi: ['がん'],
    kunyomi: ['まる'],
    type: CharacterType.KANJI,
  },
  {
    characters: '正',
    meanings: ['correct'],
    onyomi: ['せい', 'しょう'],
    kunyomi: ['ただ', 'まさ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '土',
    meanings: ['dirt', 'soil', 'earth', 'ground'],
    onyomi: ['ど', 'と'],
    kunyomi: ['つち'],
    type: CharacterType.KANJI,
  },
  {
    characters: '犬',
    meanings: ['dog'],
    onyomi: ['けん'],
    kunyomi: ['いぬ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '夕',
    meanings: ['evening'],
    onyomi: ['せき'],
    kunyomi: ['ゆう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '出',
    meanings: ['exit'],
    onyomi: ['しゅつ'],
    kunyomi: ['で', 'だ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '目',
    meanings: ['eye'],
    onyomi: ['もく'],
    kunyomi: ['め'],
    type: CharacterType.KANJI,
  },
  {
    characters: '了',
    meanings: ['finish', 'complete', 'end'],
    onyomi: ['りょう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '火',
    meanings: ['fire'],
    onyomi: ['か'],
    kunyomi: ['ひ', 'ほ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '才',
    meanings: ['genius', 'wit', 'talent', 'ability'],
    onyomi: ['さい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '手',
    meanings: ['hand'],
    onyomi: ['しゅ', 'ず'],
    kunyomi: ['て'],
    type: CharacterType.KANJI,
  },
  {
    characters: '天',
    meanings: ['heaven'],
    onyomi: ['てん'],
    kunyomi: ['あま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '王',
    meanings: ['king'],
    onyomi: ['おう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '左',
    meanings: ['left'],
    onyomi: ['さ'],
    kunyomi: ['ひだり'],
    type: CharacterType.KANJI,
  },
  {
    characters: '中',
    meanings: ['middle', 'in', 'inside', 'center'],
    onyomi: ['ちゅう'],
    kunyomi: ['なか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '月',
    meanings: ['moon', 'month'],
    onyomi: ['げつ', 'がつ'],
    kunyomi: ['つき'],
    type: CharacterType.KANJI,
  },
  {
    characters: '々',
    meanings: ['repeater', 'repetition', 'reduplication', 'iteration mark'],
    kunyomi: ['のま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '田',
    meanings: ['rice paddy', 'rice field', 'field'],
    onyomi: ['でん'],
    kunyomi: ['た'],
    type: CharacterType.KANJI,
  },
  {
    characters: '右',
    meanings: ['right'],
    onyomi: ['ゆう', 'う'],
    kunyomi: ['みぎ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '小',
    meanings: ['small', 'little'],
    onyomi: ['しょう'],
    kunyomi: ['ちい', 'こ', 'お'],
    type: CharacterType.KANJI,
  },
  {
    characters: '立',
    meanings: ['stand'],
    onyomi: ['りつ', 'りゅう'],
    kunyomi: ['た'],
    type: CharacterType.KANJI,
  },
  {
    characters: '丁',
    meanings: ['street'],
    onyomi: ['ちょう', 'てい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '日',
    meanings: ['sun', 'day'],
    onyomi: ['にち', 'じつ'],
    kunyomi: ['ひ', 'か', 'び'],
    type: CharacterType.KANJI,
  },
  {
    characters: '刀',
    meanings: ['sword', 'katana'],
    onyomi: ['とう'],
    kunyomi: ['かたな'],
    type: CharacterType.KANJI,
  },
  {
    characters: '木',
    meanings: ['tree', 'wood'],
    onyomi: ['もく', 'ぼく'],
    kunyomi: ['き', 'こ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '水',
    meanings: ['water'],
    onyomi: ['すい'],
    kunyomi: ['みず'],
    type: CharacterType.KANJI,
  },
  {
    characters: '白',
    meanings: ['white'],
    onyomi: ['はく'],
    kunyomi: ['しろ', 'しら'],
    type: CharacterType.KANJI,
  },
  {
    characters: '文',
    meanings: ['writing', 'sentence'],
    onyomi: ['ぶん', 'もん'],
    kunyomi: ['ふみ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '円',
    meanings: ['yen', 'round', 'circle'],
    onyomi: ['えん'],
    kunyomi: ['まる'],
    type: CharacterType.KANJI,
  },
  {
    characters: '矢',
    meanings: ['arrow'],
    onyomi: ['し'],
    kunyomi: ['や'],
    type: CharacterType.KANJI,
  },
  {
    characters: '市',
    meanings: ['city'],
    onyomi: ['し'],
    kunyomi: ['いち'],
    type: CharacterType.KANJI,
  },
  {
    characters: '牛',
    meanings: ['cow'],
    onyomi: ['ぎゅう'],
    kunyomi: ['うし'],
    type: CharacterType.KANJI,
  },
  {
    characters: '切',
    meanings: ['cut'],
    onyomi: ['せつ', 'さい'],
    kunyomi: ['き'],
    type: CharacterType.KANJI,
  },
  {
    characters: '方',
    meanings: ['direction', 'way'],
    onyomi: ['ほう'],
    kunyomi: ['かた'],
    type: CharacterType.KANJI,
  },
  {
    characters: '戸',
    meanings: ['door'],
    onyomi: ['こ'],
    kunyomi: ['と'],
    type: CharacterType.KANJI,
  },
  {
    characters: '太',
    meanings: ['fat'],
    onyomi: ['たい', 'た'],
    kunyomi: ['ふと'],
    nanori: ['おお'],
    type: CharacterType.KANJI,
  },
  {
    characters: '少',
    meanings: ['few', 'a little'],
    onyomi: ['しょう'],
    kunyomi: ['すこ', 'すく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '友',
    meanings: ['friend'],
    onyomi: ['ゆう'],
    kunyomi: ['とも'],
    type: CharacterType.KANJI,
  },
  {
    characters: '毛',
    meanings: ['fur', 'hair'],
    onyomi: ['もう'],
    kunyomi: ['け'],
    type: CharacterType.KANJI,
  },
  {
    characters: '半',
    meanings: ['half'],
    onyomi: ['はん'],
    kunyomi: ['なか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '心',
    meanings: ['heart'],
    onyomi: ['しん'],
    kunyomi: ['こころ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '内',
    meanings: ['inside', 'within'],
    onyomi: ['ない', 'がい'],
    kunyomi: ['うち'],
    type: CharacterType.KANJI,
  },
  {
    characters: '生',
    meanings: ['life'],
    onyomi: ['せい', 'しょう'],
    kunyomi: ['い', 'なま', 'う', 'は', 'き'],
    type: CharacterType.KANJI,
  },
  {
    characters: '台',
    meanings: ['machine', 'stand', 'basic', 'perform'],
    onyomi: ['だい', 'たい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '母',
    meanings: ['mother', 'mom'],
    onyomi: ['ぼ'],
    kunyomi: ['はは', 'かあ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '父',
    meanings: ['father', 'dad'],
    onyomi: ['ふ'],
    kunyomi: ['ちち', 'とう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '午',
    meanings: ['noon'],
    onyomi: ['ご'],
    type: CharacterType.KANJI,
  },
  {
    characters: '北',
    meanings: ['north'],
    onyomi: ['ほく'],
    kunyomi: ['きた'],
    type: CharacterType.KANJI,
  },
  {
    characters: '今',
    meanings: ['now', 'immediately'],
    onyomi: ['こん', 'きん'],
    kunyomi: ['いま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '古',
    meanings: ['old'],
    onyomi: ['こ'],
    kunyomi: ['ふる'],
    type: CharacterType.KANJI,
  },
  {
    characters: '元',
    meanings: ['origin'],
    onyomi: ['げん', 'がん'],
    kunyomi: ['もと'],
    type: CharacterType.KANJI,
  },
  {
    characters: '外',
    meanings: ['outside'],
    onyomi: ['がい', 'げ'],
    kunyomi: ['そと', 'はず', 'ほか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '分',
    meanings: ['part'],
    onyomi: ['ぶん', 'ふん', 'ぶ'],
    kunyomi: ['わ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '公',
    meanings: ['public'],
    onyomi: ['こう'],
    kunyomi: ['おおやけ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '引',
    meanings: ['pull'],
    onyomi: ['いん'],
    kunyomi: ['ひ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '止',
    meanings: ['stop'],
    onyomi: ['し'],
    kunyomi: ['と', 'や'],
    type: CharacterType.KANJI,
  },
  {
    characters: '用',
    meanings: ['task', 'use', 'business', 'errand'],
    onyomi: ['よう'],
    kunyomi: ['もち'],
    type: CharacterType.KANJI,
  },
  {
    characters: '広',
    meanings: ['wide', 'broad', 'spread'],
    onyomi: ['こう'],
    kunyomi: ['ひろ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '冬',
    meanings: ['winter'],
    onyomi: ['とう'],
    kunyomi: ['ふゆ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '氷',
    meanings: ['ice'],
    onyomi: ['ひょう'],
    kunyomi: ['こおり'],
    type: CharacterType.KANJI,
  },
  {
    characters: '金',
    meanings: ['gold'],
    onyomi: ['きん'],
    kunyomi: ['かね'],
    type: CharacterType.KANJI,
  },
  {
    characters: '休',
    meanings: ['rest'],
    onyomi: ['きゅう'],
    kunyomi: ['やす'],
    type: CharacterType.KANJI,
  },
  {
    characters: '耳',
    meanings: ['ear', 'ears'],
    onyomi: ['じ'],
    kunyomi: ['みみ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '足',
    meanings: ['foot', 'leg', 'sufficient'],
    onyomi: ['そく'],
    kunyomi: ['あし', 'た'],
    type: CharacterType.KANJI,
  },
  {
    characters: '打',
    meanings: ['hit'],
    onyomi: ['だ'],
    kunyomi: ['う', 'ぶ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '男',
    meanings: ['man', 'boy'],
    onyomi: ['だん', 'なん'],
    kunyomi: ['おとこ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '主',
    meanings: ['main', 'master'],
    onyomi: ['しゅ'],
    kunyomi: ['おも', 'ぬし', 'あるじ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '空',
    meanings: ['sky', 'empty'],
    onyomi: ['くう'],
    kunyomi: ['そら', 'あ', 'から', 'す'],
    type: CharacterType.KANJI,
  },
  {
    characters: '気',
    meanings: ['energy', 'spirit'],
    onyomi: ['き', 'け'],
    kunyomi: ['いき'],
    type: CharacterType.KANJI,
  },
  {
    characters: '見',
    meanings: ['see'],
    onyomi: ['けん'],
    kunyomi: ['み'],
    type: CharacterType.KANJI,
  },
  {
    characters: '雨',
    meanings: ['rain'],
    onyomi: ['う'],
    kunyomi: ['あめ', 'あま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '林',
    meanings: ['forest', 'grove'],
    onyomi: ['りん'],
    kunyomi: ['はやし'],
    type: CharacterType.KANJI,
  },
  {
    characters: '森',
    meanings: ['forest', 'woods'],
    onyomi: ['しん'],
    kunyomi: ['もり'],
    type: CharacterType.KANJI,
  },
  {
    characters: '石',
    meanings: ['stone'],
    onyomi: ['せき'],
    kunyomi: ['いし', 'こく', 'しゃく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '花',
    meanings: ['flower'],
    onyomi: ['か', 'け'],
    kunyomi: ['はな'],
    type: CharacterType.KANJI,
  },
  {
    characters: '虫',
    meanings: ['insect', 'bug'],
    onyomi: ['ちゅう', 'き'],
    kunyomi: ['むし'],
    type: CharacterType.KANJI,
  },
  {
    characters: '町',
    meanings: ['town'],
    onyomi: ['ちょう'],
    kunyomi: ['まち'],
    type: CharacterType.KANJI,
  },
  {
    characters: '村',
    meanings: ['village'],
    onyomi: ['そん'],
    kunyomi: ['むら'],
    type: CharacterType.KANJI,
  },
  {
    characters: '赤',
    meanings: ['red'],
    onyomi: ['せき'],
    kunyomi: ['あか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '青',
    meanings: ['blue'],
    onyomi: ['せい', 'しょう'],
    kunyomi: ['あお'],
    type: CharacterType.KANJI,
  },
  {
    characters: '先',
    meanings: ['previous', 'ahead', 'past', 'former'],
    onyomi: ['せん'],
    kunyomi: ['さき', 'まず'],
    type: CharacterType.KANJI,
  },
  {
    characters: '早',
    meanings: ['early', 'fast', 'quick'],
    onyomi: ['そう'],
    kunyomi: ['はや', 'さ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '名',
    meanings: ['name', 'famous'],
    onyomi: ['めい', 'みょう'],
    kunyomi: ['な'],
    type: CharacterType.KANJI,
  },
  {
    characters: '不',
    meanings: ['not'],
    onyomi: ['ふ', 'ぶ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '号',
    meanings: ['number'],
    onyomi: ['ごう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '他',
    meanings: ['other'],
    onyomi: ['た'],
    kunyomi: ['ほか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '去',
    meanings: ['past'],
    onyomi: ['きょ', 'こ'],
    kunyomi: ['さ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '皿',
    meanings: ['plate'],
    kunyomi: ['さら'],
    type: CharacterType.KANJI,
  },
  {
    characters: '申',
    meanings: ['say', 'say humbly', 'humbly say'],
    onyomi: ['しん'],
    kunyomi: ['もう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '代',
    meanings: ['substitute', 'replace', 'period', 'age'],
    onyomi: ['だい', 'たい'],
    kunyomi: ['か', 'かわ', 'よ', 'しろ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '礼',
    meanings: ['thanks'],
    onyomi: ['れい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '宝',
    meanings: ['treasure'],
    onyomi: ['ほう'],
    kunyomi: ['たから'],
    type: CharacterType.KANJI,
  },
  {
    characters: '世',
    meanings: ['world', 'generation'],
    onyomi: ['せい', 'せ'],
    kunyomi: ['よ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '校',
    meanings: ['school'],
    onyomi: ['こう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '字',
    meanings: ['letter', 'character', 'symbol'],
    onyomi: ['じ'],
    kunyomi: ['あざ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '学',
    meanings: ['study', 'learn', 'learning'],
    onyomi: ['がく'],
    kunyomi: ['まな'],
    type: CharacterType.KANJI,
  },
  {
    characters: '年',
    meanings: ['year'],
    onyomi: ['ねん'],
    kunyomi: ['とし'],
    type: CharacterType.KANJI,
  },
  {
    characters: '音',
    meanings: ['sound'],
    onyomi: ['おん', 'いん'],
    kunyomi: ['おと', 'ね'],
    type: CharacterType.KANJI,
  },
  {
    characters: '糸',
    meanings: ['thread'],
    onyomi: ['し'],
    kunyomi: ['いと'],
    type: CharacterType.KANJI,
  },
  {
    characters: '車',
    meanings: ['car'],
    onyomi: ['しゃ'],
    kunyomi: ['くるま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '央',
    meanings: ['center', 'centre'],
    onyomi: ['おう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '写',
    meanings: ['copy'],
    onyomi: ['しゃ'],
    kunyomi: ['うつ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '仕',
    meanings: ['doing', 'do'],
    onyomi: ['し'],
    kunyomi: ['つか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '平',
    meanings: ['flat', 'peace'],
    onyomi: ['へい', 'ひょう', 'びょう'],
    kunyomi: ['たい', 'ひら'],
    type: CharacterType.KANJI,
  },
  {
    characters: '貝',
    meanings: ['shell', 'shellfish'],
    kunyomi: ['かい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '草',
    meanings: ['grass', 'weed'],
    onyomi: ['そう'],
    kunyomi: ['くさ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '竹',
    meanings: ['bamboo'],
    kunyomi: ['たけ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '雲',
    meanings: ['cloud'],
    onyomi: ['うん'],
    kunyomi: ['くも'],
    type: CharacterType.KANJI,
  },
  {
    characters: '何',
    meanings: ['what'],
    onyomi: ['か'],
    kunyomi: ['なに', 'なん'],
    type: CharacterType.KANJI,
  },
  {
    characters: '科',
    meanings: ['science', 'course', 'department'],
    onyomi: ['か'],
    type: CharacterType.KANJI,
  },
  {
    characters: '遠',
    meanings: ['far'],
    onyomi: ['えん'],
    kunyomi: ['とお'],
    type: CharacterType.KANJI,
  },
  {
    characters: '夏',
    meanings: ['summer'],
    onyomi: ['げ', 'か', 'が'],
    kunyomi: ['なつ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '家',
    meanings: ['house', 'home'],
    onyomi: ['か', 'け'],
    kunyomi: ['いえ', 'や', 'うち'],
    type: CharacterType.KANJI,
  },
  {
    characters: '歌',
    meanings: ['song', 'sing'],
    onyomi: ['か'],
    kunyomi: ['うた'],
    type: CharacterType.KANJI,
  },
  {
    characters: '画',
    meanings: ['drawing', 'picture', 'painting', 'stroke'],
    onyomi: ['が', 'かく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '会',
    meanings: ['meet'],
    onyomi: ['かい'],
    kunyomi: ['あ', 'え'],
    type: CharacterType.KANJI,
  },
  {
    characters: '海',
    meanings: ['sea', 'ocean'],
    onyomi: ['かい'],
    kunyomi: ['うみ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '回',
    meanings: ['times', 'revolve', 'turn', 'go around'],
    onyomi: ['かい'],
    kunyomi: ['まわ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '絵',
    meanings: ['drawing', 'picture', 'painting'],
    onyomi: ['かい', 'え'],
    type: CharacterType.KANJI,
  },
  {
    characters: '園',
    meanings: ['garden', 'park'],
    onyomi: ['えん'],
    kunyomi: ['その'],
    type: CharacterType.KANJI,
  },
  {
    characters: '間',
    meanings: ['interval', 'space'],
    onyomi: ['かん', 'けん'],
    kunyomi: ['あいだ', 'ま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '顔',
    meanings: ['face'],
    onyomi: ['がん'],
    kunyomi: ['かお'],
    type: CharacterType.KANJI,
  },
  {
    characters: '汽',
    meanings: ['steam', 'vapor'],
    onyomi: ['き'],
    type: CharacterType.KANJI,
  },
  {
    characters: '記',
    meanings: ['write down', 'record', 'chronicle'],
    onyomi: ['き'],
    kunyomi: ['しる'],
    type: CharacterType.KANJI,
  },
  {
    characters: '帰',
    meanings: ['return', 'return home'],
    onyomi: ['き'],
    kunyomi: ['かえ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '魚',
    meanings: ['fish'],
    onyomi: ['ぎょ'],
    kunyomi: ['うお', 'さかな'],
    type: CharacterType.KANJI,
  },
  {
    characters: '京',
    meanings: ['capital'],
    onyomi: ['きょう', 'けい'],
    kunyomi: ['みやこ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '教',
    meanings: ['teach'],
    onyomi: ['きょう'],
    kunyomi: ['おし', 'おそ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '強',
    meanings: ['strong', 'strength', 'strengthen'],
    onyomi: ['きょう', 'ごう'],
    kunyomi: ['つよ', 'し'],
    type: CharacterType.KANJI,
  },
  {
    characters: '角',
    meanings: ['angle', 'corner', 'antler'],
    onyomi: ['かく'],
    kunyomi: ['かど', 'つの'],
    type: CharacterType.KANJI,
  },
  {
    characters: '斤',
    meanings: ['axe', 'bread loaf counter'],
    onyomi: ['きん'],
    type: CharacterType.KANJI,
  },
  {
    characters: '近',
    meanings: ['near', 'close'],
    onyomi: ['きん', 'こん'],
    kunyomi: ['ちか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '形',
    meanings: ['shape', 'form', 'type', 'figure', 'appearance'],
    onyomi: ['けい', 'ぎょう'],
    kunyomi: ['かた', 'かたち'],
    type: CharacterType.KANJI,
  },
  {
    characters: '皮',
    meanings: ['skin'],
    onyomi: ['ひ'],
    kunyomi: ['かわ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '計',
    meanings: ['measure', 'measurement', 'plan'],
    onyomi: ['けい'],
    kunyomi: ['はか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '語',
    meanings: ['language', 'speak', 'word'],
    onyomi: ['ご'],
    kunyomi: ['かた'],
    type: CharacterType.KANJI,
  },
  {
    characters: '原',
    meanings: ['original', 'fundamental', 'field'],
    onyomi: ['げん'],
    kunyomi: ['はら'],
    type: CharacterType.KANJI,
  },
  {
    characters: '後',
    meanings: ['after', 'behind', 'back', 'later'],
    onyomi: ['ご', 'こう'],
    kunyomi: ['のち', 'うし', 'あと', 'おく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '交',
    meanings: ['mix', 'mingle', 'exchange', 'intercourse'],
    onyomi: ['こう'],
    kunyomi: ['まじ', 'ま', 'か'],
    type: CharacterType.KANJI,
  },
  {
    characters: '光',
    meanings: ['sunlight', 'light', 'shine', 'brilliance'],
    onyomi: ['こう'],
    kunyomi: ['ひかり', 'ひか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '行',
    meanings: ['go', 'do', 'conduct', 'stroke'],
    onyomi: ['こう', 'ぎょう'],
    kunyomi: ['い', 'ゆ', 'おこな'],
    type: CharacterType.KANJI,
  },
  {
    characters: '考',
    meanings: ['think', 'consider'],
    onyomi: ['こう'],
    kunyomi: ['かんが'],
    type: CharacterType.KANJI,
  },
  {
    characters: '高',
    meanings: ['tall', 'expensive', 'high'],
    onyomi: ['こう'],
    kunyomi: ['たか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '黄',
    meanings: ['yellow'],
    onyomi: ['こう', 'おう'],
    kunyomi: ['き', 'こ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '合',
    meanings: ['combine', 'join', 'union', 'fit', 'suit'],
    onyomi: ['ごう', 'がっ', 'かっ'],
    kunyomi: ['あ', 'あい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '谷',
    meanings: ['valley'],
    onyomi: ['こく'],
    kunyomi: ['たに'],
    nanori: ['せ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '国',
    meanings: ['country', 'nation'],
    onyomi: ['こく'],
    kunyomi: ['くに'],
    type: CharacterType.KANJI,
  },
  {
    characters: '黒',
    meanings: ['black'],
    onyomi: ['こく'],
    kunyomi: ['くろ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '作',
    meanings: ['make', 'work'],
    onyomi: ['さく', 'さ'],
    kunyomi: ['つく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '算',
    meanings: ['calculate', 'count'],
    onyomi: ['さん'],
    kunyomi: ['そろ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '自',
    meanings: ['oneself', 'self'],
    onyomi: ['じ', 'し'],
    kunyomi: ['みずか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '寺',
    meanings: ['temple'],
    onyomi: ['じ'],
    kunyomi: ['てら'],
    type: CharacterType.KANJI,
  },
  {
    characters: '時',
    meanings: ['time', `o'clock`, 'hour', 'occasion'],
    onyomi: ['じ'],
    kunyomi: ['とき'],
    type: CharacterType.KANJI,
  },
  {
    characters: '思',
    meanings: ['think', 'thought'],
    onyomi: ['し'],
    kunyomi: ['おも'],
    type: CharacterType.KANJI,
  },
  {
    characters: '紙',
    meanings: ['paper'],
    onyomi: ['し'],
    kunyomi: ['かみ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '室',
    meanings: ['room'],
    onyomi: ['しつ'],
    kunyomi: ['むろ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '社',
    meanings: ['shrine', 'company', 'society'],
    onyomi: ['しゃ'],
    kunyomi: ['やしろ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '弱',
    meanings: ['weak'],
    onyomi: ['じゃく'],
    kunyomi: ['よわ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '首',
    meanings: ['neck'],
    onyomi: ['しゅ'],
    kunyomi: ['くび'],
    type: CharacterType.KANJI,
  },
  {
    characters: '秋',
    meanings: ['autumn', 'fall'],
    onyomi: ['しゅう'],
    kunyomi: ['あき'],
    type: CharacterType.KANJI,
  },
  {
    characters: '春',
    meanings: ['spring'],
    onyomi: ['しゅん'],
    kunyomi: ['はる'],
    type: CharacterType.KANJI,
  },
  {
    characters: '書',
    meanings: ['write', 'writing', 'book'],
    onyomi: ['しょ'],
    kunyomi: ['か'],
    type: CharacterType.KANJI,
  },
  {
    characters: '場',
    meanings: ['location', 'place'],
    onyomi: ['じょう'],
    kunyomi: ['ば'],
    type: CharacterType.KANJI,
  },
  {
    characters: '色',
    meanings: ['color'],
    onyomi: ['しき', 'しょく'],
    kunyomi: ['いろ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '食',
    meanings: ['eat', 'meal'],
    onyomi: ['しょく', 'じき'],
    kunyomi: ['た', 'く'],
    type: CharacterType.KANJI,
  },
  {
    characters: '新',
    meanings: ['new', 'fresh', 'novel'],
    onyomi: ['しん'],
    kunyomi: ['あたら', 'あら', 'にい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '親',
    meanings: ['parent', 'intimate'],
    onyomi: ['しん'],
    kunyomi: ['おや', 'した'],
    type: CharacterType.KANJI,
  },
  {
    characters: '図',
    meanings: ['diagram', 'figure', 'drawing'],
    onyomi: ['ず', 'と'],
    kunyomi: ['え', 'はか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '数',
    meanings: ['count', 'number', 'amount'],
    onyomi: ['すう'],
    kunyomi: ['かぞ', 'かず'],
    type: CharacterType.KANJI,
  },
  {
    characters: '西',
    meanings: ['west'],
    onyomi: ['せい', 'さい'],
    kunyomi: ['にし'],
    type: CharacterType.KANJI,
  },
  {
    characters: '声',
    meanings: ['voice', 'reputation'],
    onyomi: ['せい'],
    kunyomi: ['こえ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '星',
    meanings: ['star'],
    onyomi: ['せい'],
    kunyomi: ['ほし'],
    type: CharacterType.KANJI,
  },
  {
    characters: '晴',
    meanings: ['clear up', 'clear'],
    onyomi: ['せい'],
    kunyomi: ['は'],
    type: CharacterType.KANJI,
  },
  {
    characters: '楽',
    meanings: ['comfort', 'ease', 'pleasure', 'enjoyable'],
    onyomi: ['らく', 'がく'],
    kunyomi: ['たの'],
    type: CharacterType.KANJI,
  },
  {
    characters: '多',
    meanings: ['many', 'much', 'lots of', 'multiple'],
    onyomi: ['た'],
    kunyomi: ['おお'],
    type: CharacterType.KANJI,
  },
  {
    characters: '明',
    meanings: ['bright', 'light', 'clear'],
    onyomi: ['めい', 'みょう', 'みん'],
    kunyomi: ['あ', 'あか', 'あき'],
    type: CharacterType.KANJI,
  },
  {
    characters: '細',
    meanings: ['thin', 'narrow', 'fine'],
    onyomi: ['さい'],
    kunyomi: ['ほそ', 'こま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '長',
    meanings: ['long', 'far', 'chief', 'leader'],
    onyomi: ['ちょう'],
    kunyomi: ['なが'],
    nanori: ['は'],
    type: CharacterType.KANJI,
  },
  {
    characters: '体',
    meanings: ['body', 'style'],
    onyomi: ['たい'],
    kunyomi: ['からだ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '頭',
    meanings: ['head'],
    onyomi: ['ず', 'とう', 'と'],
    kunyomi: ['あたま', 'かしら'],
    type: CharacterType.KANJI,
  },
  {
    characters: '兄',
    meanings: ['older brother', 'elder brother', 'big brother'],
    onyomi: ['きょう', 'けい'],
    kunyomi: ['あに', 'にい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '弟',
    meanings: ['younger brother', 'little brother'],
    onyomi: ['だい', 'で', 'てい'],
    kunyomi: ['おとうと'],
    type: CharacterType.KANJI,
  },
  {
    characters: '姉',
    meanings: ['older sister', 'big sister', 'elder sister'],
    onyomi: ['し'],
    kunyomi: ['お', 'あね', 'ねえ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '妹',
    meanings: ['younger sister', 'little sister'],
    onyomi: ['まい'],
    kunyomi: ['いもうと'],
    type: CharacterType.KANJI,
  },
  {
    characters: '通',
    meanings: ['pass', 'pass through', 'go to and from'],
    onyomi: ['つう', 'つ'],
    kunyomi: ['とお', 'かよ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '走',
    meanings: ['run'],
    onyomi: ['そう'],
    kunyomi: ['はし'],
    type: CharacterType.KANJI,
  },
  {
    characters: '歩',
    meanings: ['walk', 'step', 'rate'],
    onyomi: ['ほ', 'ぶ', 'ふ'],
    kunyomi: ['ある', 'あゆ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '来',
    meanings: ['come', 'next', 'since'],
    onyomi: ['らい'],
    kunyomi: ['く', 'きた'],
    type: CharacterType.KANJI,
  },
  {
    characters: '売',
    meanings: ['sell'],
    onyomi: ['ばい'],
    kunyomi: ['う'],
    type: CharacterType.KANJI,
  },
  {
    characters: '買',
    meanings: ['buy'],
    onyomi: ['ばい'],
    kunyomi: ['か'],
    type: CharacterType.KANJI,
  },
  {
    characters: '読',
    meanings: ['read'],
    onyomi: ['とう', 'どく', 'とく'],
    kunyomi: ['よ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '当',
    meanings: ['correct', 'right', 'success', 'hit', 'appropriate'],
    onyomi: ['とう'],
    kunyomi: ['あ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '直',
    meanings: ['fix', 'direct', 'soon', 'honestly'],
    onyomi: ['ちょく', 'じき'],
    kunyomi: ['ただ', 'なお'],
    type: CharacterType.KANJI,
  },
  {
    characters: '活',
    meanings: ['lively', 'live', 'life'],
    onyomi: ['かつ'],
    kunyomi: ['い'],
    type: CharacterType.KANJI,
  },
  {
    characters: '聞',
    meanings: ['hear', 'listen to', 'ask'],
    onyomi: ['ぶん', 'もん'],
    kunyomi: ['き'],
    type: CharacterType.KANJI,
  },
  {
    characters: '言',
    meanings: ['say', 'speak', 'word'],
    onyomi: ['げん', 'ごん'],
    kunyomi: ['い', 'こと'],
    type: CharacterType.KANJI,
  },
  {
    characters: '話',
    meanings: ['story', 'conversation', 'talk', 'speak'],
    onyomi: ['わ'],
    kunyomi: ['はな', 'はなし'],
    type: CharacterType.KANJI,
  },
  {
    characters: '答',
    meanings: ['answer', 'response', 'reply'],
    onyomi: ['とう'],
    kunyomi: ['こた'],
    type: CharacterType.KANJI,
  },
  {
    characters: '知',
    meanings: ['know', 'knowledge'],
    onyomi: ['ち'],
    kunyomi: ['し'],
    type: CharacterType.KANJI,
  },
  {
    characters: '肉',
    meanings: ['meat'],
    onyomi: ['にく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '麦',
    meanings: ['wheat', 'barley', 'oats'],
    onyomi: ['ばく'],
    kunyomi: ['むぎ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '米',
    meanings: ['rice', 'america'],
    onyomi: ['べい', 'まい'],
    kunyomi: ['こめ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '鳥',
    meanings: ['bird'],
    onyomi: ['ちょう'],
    kunyomi: ['とり'],
    type: CharacterType.KANJI,
  },
  {
    characters: '鳴',
    meanings: ['chirp', 'sing', 'howl'],
    onyomi: ['めい'],
    kunyomi: ['な'],
    type: CharacterType.KANJI,
  },
  {
    characters: '馬',
    meanings: ['horse'],
    onyomi: ['ば', 'め'],
    kunyomi: ['うま', 'ま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '組',
    meanings: ['group', 'association', 'team', 'construct', 'assemble'],
    onyomi: ['そ'],
    kunyomi: ['く', 'くみ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '番',
    meanings: [
      'number in a series',
      'turn',
      'ordinal number',
      'number',
      'watch',
      'guard',
    ],
    onyomi: ['ばん'],
    kunyomi: ['つが', 'つがい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '点',
    meanings: ['point', 'dot', 'mark'],
    onyomi: ['てん'],
    kunyomi: ['つ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '羽',
    meanings: ['feather', 'feathers', 'wing', 'wing'],
    onyomi: ['う'],
    kunyomi: ['はね', 'は', 'わ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '週',
    meanings: ['week'],
    onyomi: ['しゅう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '曜',
    meanings: ['day of the week', 'weekday'],
    onyomi: ['よう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '毎',
    meanings: ['every', 'each'],
    onyomi: ['まい'],
    kunyomi: ['ごと'],
    type: CharacterType.KANJI,
  },
  {
    characters: '東',
    meanings: ['east'],
    onyomi: ['とう'],
    kunyomi: ['ひがし'],
    type: CharacterType.KANJI,
  },
  {
    characters: '南',
    meanings: ['south'],
    onyomi: ['なん'],
    kunyomi: ['みなみ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '風',
    meanings: ['wind', 'style'],
    onyomi: ['ふう', 'ふ'],
    kunyomi: ['かぜ', 'かざ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '雪',
    meanings: ['snow'],
    onyomi: ['せつ'],
    kunyomi: ['ゆき'],
    type: CharacterType.KANJI,
  },
  {
    characters: '岩',
    meanings: ['boulder', 'rock'],
    onyomi: ['がん'],
    kunyomi: ['いわ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '門',
    meanings: ['gate', 'gates'],
    onyomi: ['もん'],
    kunyomi: ['と', 'かど'],
    type: CharacterType.KANJI,
  },
  {
    characters: '店',
    meanings: ['shop', 'store'],
    onyomi: ['てん'],
    kunyomi: ['みせ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '里',
    meanings: ['village', 'hometown'],
    onyomi: ['り'],
    kunyomi: ['さと'],
    type: CharacterType.KANJI,
  },
  {
    characters: '野',
    meanings: ['field', 'plains'],
    onyomi: ['や'],
    kunyomi: ['の'],
    type: CharacterType.KANJI,
  },
  {
    characters: '道',
    meanings: ['road', 'street', 'path', 'way'],
    onyomi: ['どう', 'とう'],
    kunyomi: ['みち'],
    type: CharacterType.KANJI,
  },
  {
    characters: '地',
    meanings: ['earth', 'ground', 'land'],
    onyomi: ['ち', 'じ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '池',
    meanings: ['pond'],
    onyomi: ['ち'],
    kunyomi: ['いけ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '茶',
    meanings: ['tea'],
    onyomi: ['ちゃ', 'さ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '線',
    meanings: ['line'],
    onyomi: ['せん'],
    type: CharacterType.KANJI,
  },
  {
    characters: '朝',
    meanings: ['morning'],
    onyomi: ['ちょう'],
    kunyomi: ['あさ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '昼',
    meanings: ['noon', 'midday'],
    onyomi: ['ちゅう'],
    kunyomi: ['ひる'],
    type: CharacterType.KANJI,
  },
  {
    characters: '夜',
    meanings: ['night', 'evening'],
    onyomi: ['や'],
    kunyomi: ['よ', 'よる'],
    type: CharacterType.KANJI,
  },
  {
    characters: '前',
    meanings: ['before', 'front'],
    onyomi: ['ぜん'],
    kunyomi: ['まえ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '理',
    meanings: ['reason', 'justice'],
    onyomi: ['り'],
    kunyomi: ['ことわり'],
    type: CharacterType.KANJI,
  },
  {
    characters: '電',
    meanings: ['electricity'],
    onyomi: ['でん'],
    type: CharacterType.KANJI,
  },
  {
    characters: '船',
    meanings: ['boat', 'ship', 'vessel'],
    onyomi: ['せん'],
    kunyomi: ['ふね'],
    type: CharacterType.KANJI,
  },
  {
    characters: '同',
    meanings: ['same', 'similar'],
    onyomi: ['どう'],
    kunyomi: ['おな'],
    type: CharacterType.KANJI,
  },
  {
    characters: '全',
    meanings: ['all', 'whole'],
    onyomi: ['ぜん'],
    kunyomi: ['すべ', 'まった'],
    type: CharacterType.KANJI,
  },
  {
    characters: '血',
    meanings: ['blood'],
    onyomi: ['けつ'],
    kunyomi: ['ち'],
    type: CharacterType.KANJI,
  },
  {
    characters: '両',
    meanings: ['both'],
    onyomi: ['りょう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '化',
    meanings: ['change'],
    onyomi: ['か'],
    kunyomi: ['ば'],
    type: CharacterType.KANJI,
  },
  {
    characters: '亡',
    meanings: ['death', 'deceased'],
    onyomi: ['ぼう'],
    kunyomi: ['な'],
    type: CharacterType.KANJI,
  },
  {
    characters: '死',
    meanings: ['death'],
    onyomi: ['し'],
    kunyomi: ['し'],
    type: CharacterType.KANJI,
  },
  {
    characters: '有',
    meanings: ['have'],
    onyomi: ['ゆう', 'う'],
    kunyomi: ['あ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '私',
    meanings: ['i', 'private'],
    onyomi: ['し'],
    kunyomi: ['わたし'],
    type: CharacterType.KANJI,
  },
  {
    characters: '曲',
    meanings: ['music', 'bend'],
    onyomi: ['きょく'],
    kunyomi: ['ま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '次',
    meanings: ['next'],
    onyomi: ['じ'],
    kunyomi: ['つぎ', 'つ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '安',
    meanings: ['relax', 'cheap'],
    onyomi: ['あん'],
    kunyomi: ['やす'],
    type: CharacterType.KANJI,
  },
  {
    characters: '羊',
    meanings: ['sheep'],
    onyomi: ['よう'],
    kunyomi: ['ひつじ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '州',
    meanings: ['state', 'province', 'county'],
    onyomi: ['しゅう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '向',
    meanings: ['yonder', 'facing'],
    onyomi: ['こう'],
    kunyomi: ['む'],
    nanori: ['なた'],
    type: CharacterType.KANJI,
  },
  {
    characters: '辺',
    meanings: ['area'],
    onyomi: ['へん'],
    kunyomi: ['あた', 'べ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '付',
    meanings: ['attach'],
    onyomi: ['ふ'],
    kunyomi: ['つ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '札',
    meanings: ['bill', 'tag', 'label', 'note'],
    onyomi: ['さつ'],
    kunyomi: ['ふだ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '必',
    meanings: ['certain'],
    onyomi: ['ひつ'],
    kunyomi: ['かなら'],
    type: CharacterType.KANJI,
  },
  {
    characters: '末',
    meanings: ['end'],
    onyomi: ['まつ'],
    kunyomi: ['すえ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '氏',
    meanings: ['last name', 'surname', 'family name'],
    onyomi: ['し'],
    kunyomi: ['うじ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '失',
    meanings: ['fault'],
    onyomi: ['しつ'],
    kunyomi: ['うしな'],
    type: CharacterType.KANJI,
  },
  {
    characters: '以',
    meanings: ['from', 'since', 'compared with', 'by means of'],
    onyomi: ['い'],
    type: CharacterType.KANJI,
  },
  {
    characters: '欠',
    meanings: ['lack'],
    onyomi: ['けつ'],
    kunyomi: ['か'],
    type: CharacterType.KANJI,
  },
  {
    characters: '未',
    meanings: ['not yet'],
    onyomi: ['み'],
    kunyomi: ['ま', 'いま', 'ひつじ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '民',
    meanings: ['people', 'peoples', 'nation'],
    onyomi: ['みん'],
    kunyomi: ['たみ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '由',
    meanings: ['reason'],
    onyomi: ['ゆう', 'ゆ', 'ゆい'],
    kunyomi: ['よし', 'よ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '反',
    meanings: ['anti'],
    onyomi: ['はん'],
    type: CharacterType.KANJI,
  },
  {
    characters: '君',
    meanings: ['buddy'],
    onyomi: ['くん'],
    kunyomi: ['きみ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '局',
    meanings: ['bureau', 'department'],
    onyomi: ['きょく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '決',
    meanings: ['decide', 'decision'],
    onyomi: ['けつ'],
    kunyomi: ['き'],
    type: CharacterType.KANJI,
  },
  {
    characters: '住',
    meanings: ['dwelling', 'reside', 'dwell'],
    onyomi: ['じゅう'],
    kunyomi: ['す'],
    type: CharacterType.KANJI,
  },
  {
    characters: '助',
    meanings: ['help'],
    onyomi: ['じょ'],
    kunyomi: ['たす', 'すけ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '医',
    meanings: ['medicine'],
    onyomi: ['い'],
    type: CharacterType.KANJI,
  },
  {
    characters: '所',
    meanings: ['place'],
    onyomi: ['しょ'],
    kunyomi: ['ところ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '究',
    meanings: ['research'],
    onyomi: ['きゅう'],
    kunyomi: ['きわ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '役',
    meanings: ['service', 'duty'],
    onyomi: ['やく', 'えき'],
    type: CharacterType.KANJI,
  },
  {
    characters: '研',
    meanings: ['sharpen'],
    onyomi: ['けん'],
    kunyomi: ['と'],
    type: CharacterType.KANJI,
  },
  {
    characters: '身',
    meanings: ['somebody', 'someone', 'body'],
    onyomi: ['しん'],
    kunyomi: ['み'],
    type: CharacterType.KANJI,
  },
  {
    characters: '者',
    meanings: ['someone', 'somebody'],
    onyomi: ['しゃ'],
    kunyomi: ['もの'],
    type: CharacterType.KANJI,
  },
  {
    characters: '支',
    meanings: ['support', 'branch'],
    onyomi: ['し'],
    kunyomi: ['ささ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '投',
    meanings: ['throw'],
    onyomi: ['とう'],
    kunyomi: ['な'],
    type: CharacterType.KANJI,
  },
  {
    characters: '対',
    meanings: ['versus', 'opposite'],
    onyomi: ['たい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '受',
    meanings: ['accept', 'receive'],
    onyomi: ['じゅ'],
    kunyomi: ['う'],
    type: CharacterType.KANJI,
  },
  {
    characters: '事',
    meanings: ['action', 'matter', 'thing'],
    onyomi: ['じ'],
    kunyomi: ['こと', 'つか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '美',
    meanings: ['beauty', 'beautiful'],
    onyomi: ['び', 'み'],
    kunyomi: ['うつく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '予',
    meanings: ['beforehand'],
    onyomi: ['よ'],
    kunyomi: ['あらかじ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '服',
    meanings: ['clothes', 'clothing'],
    onyomi: ['ふく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '度',
    meanings: ['degrees', 'occurrence'],
    onyomi: ['ど', 'たく'],
    kunyomi: ['たび'],
    type: CharacterType.KANJI,
  },
  {
    characters: '発',
    meanings: ['departure'],
    onyomi: ['はつ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '定',
    meanings: ['determine'],
    onyomi: ['てい', 'じょう'],
    kunyomi: ['さだ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '談',
    meanings: ['discuss'],
    onyomi: ['だん'],
    type: CharacterType.KANJI,
  },
  {
    characters: '表',
    meanings: ['express'],
    onyomi: ['ひょう'],
    kunyomi: ['あらわ', 'おもて'],
    type: CharacterType.KANJI,
  },
  {
    characters: '客',
    meanings: ['guest', 'customer'],
    onyomi: ['きゃく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '重',
    meanings: ['heavy'],
    onyomi: ['じゅう', 'ちょう'],
    kunyomi: ['おも', 'かさ', 'え'],
    type: CharacterType.KANJI,
  },
  {
    characters: '持',
    meanings: ['hold'],
    onyomi: ['じ'],
    kunyomi: ['も'],
    type: CharacterType.KANJI,
  },
  {
    characters: '負',
    meanings: ['lose'],
    onyomi: ['ふ'],
    kunyomi: ['ま', 'お'],
    type: CharacterType.KANJI,
  },
  {
    characters: '相',
    meanings: ['mutual'],
    onyomi: ['そう', 'しょう'],
    kunyomi: ['あい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '要',
    meanings: ['need'],
    onyomi: ['よう'],
    kunyomi: ['い', 'かなめ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '部',
    meanings: ['part', 'department', 'club'],
    onyomi: ['ぶ'],
    kunyomi: ['へ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '和',
    meanings: ['peace', 'japanese style'],
    onyomi: ['わ', 'お'],
    kunyomi: ['なご', 'やわ'],
    nanori: ['かず', 'より'],
    type: CharacterType.KANJI,
  },
  {
    characters: '県',
    meanings: ['prefecture'],
    onyomi: ['けん'],
    type: CharacterType.KANJI,
  },
  {
    characters: '保',
    meanings: ['preserve', 'guarantee'],
    onyomi: ['ほ'],
    kunyomi: ['たも'],
    type: CharacterType.KANJI,
  },
  {
    characters: '返',
    meanings: ['return'],
    onyomi: ['へん'],
    kunyomi: ['かえ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '乗',
    meanings: ['ride'],
    onyomi: ['じょう'],
    kunyomi: ['の'],
    type: CharacterType.KANJI,
  },
  {
    characters: '屋',
    meanings: ['roof', 'shop', 'store'],
    onyomi: ['おく'],
    kunyomi: ['や'],
    type: CharacterType.KANJI,
  },
  {
    characters: '送',
    meanings: ['send'],
    onyomi: ['そう'],
    kunyomi: ['おく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '苦',
    meanings: ['suffering'],
    onyomi: ['く'],
    kunyomi: ['くる', 'にが'],
    type: CharacterType.KANJI,
  },
  {
    characters: '泳',
    meanings: ['swim'],
    onyomi: ['えい'],
    kunyomi: ['およ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '仮',
    meanings: ['temporary'],
    onyomi: ['か'],
    kunyomi: ['かり'],
    type: CharacterType.KANJI,
  },
  {
    characters: '験',
    meanings: ['test'],
    onyomi: ['けん'],
    kunyomi: ['ため', 'ためし'],
    type: CharacterType.KANJI,
  },
  {
    characters: '物',
    meanings: ['thing'],
    onyomi: ['ぶつ', 'もつ'],
    kunyomi: ['もの'],
    type: CharacterType.KANJI,
  },
  {
    characters: '具',
    meanings: ['tool'],
    onyomi: ['ぐ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '実',
    meanings: ['truth', 'reality'],
    onyomi: ['じつ'],
    kunyomi: ['み', 'みの'],
    type: CharacterType.KANJI,
  },
  {
    characters: '試',
    meanings: ['try', 'attempt'],
    onyomi: ['し'],
    kunyomi: ['こころ', 'ため'],
    type: CharacterType.KANJI,
  },
  {
    characters: '使',
    meanings: ['use'],
    onyomi: ['し'],
    kunyomi: ['つか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '勝',
    meanings: ['win', 'victory'],
    onyomi: ['しょう'],
    kunyomi: ['か'],
    type: CharacterType.KANJI,
  },
  {
    characters: '界',
    meanings: ['world'],
    onyomi: ['かい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '進',
    meanings: ['advance'],
    onyomi: ['しん'],
    kunyomi: ['すす'],
    type: CharacterType.KANJI,
  },
  {
    characters: '酒',
    meanings: ['alcohol'],
    onyomi: ['しゅ'],
    kunyomi: ['さけ', 'さか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '始',
    meanings: ['begin', 'start'],
    onyomi: ['し'],
    kunyomi: ['はじ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '業',
    meanings: ['business'],
    onyomi: ['ぎょう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '運',
    meanings: ['carry', 'luck'],
    onyomi: ['うん'],
    kunyomi: ['はこ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '漢',
    meanings: ['chinese', 'china'],
    onyomi: ['かん'],
    type: CharacterType.KANJI,
  },
  {
    characters: '集',
    meanings: ['collect', 'gather'],
    onyomi: ['しゅう'],
    kunyomi: ['あつ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '配',
    meanings: ['distribute'],
    onyomi: ['はい'],
    kunyomi: ['くば'],
    type: CharacterType.KANJI,
  },
  {
    characters: '飲',
    meanings: ['drink'],
    onyomi: ['いん'],
    kunyomi: ['の'],
    type: CharacterType.KANJI,
  },
  {
    characters: '終',
    meanings: ['end', 'finish'],
    onyomi: ['しゅう'],
    kunyomi: ['おわ', 'お'],
    type: CharacterType.KANJI,
  },
  {
    characters: '落',
    meanings: ['fall'],
    onyomi: ['らく'],
    kunyomi: ['お'],
    type: CharacterType.KANJI,
  },
  {
    characters: '農',
    meanings: ['farming', 'agriculture'],
    onyomi: ['のう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '速',
    meanings: ['fast'],
    onyomi: ['そく'],
    kunyomi: ['はや'],
    type: CharacterType.KANJI,
  },
  {
    characters: '院',
    meanings: ['institution'],
    onyomi: ['いん'],
    type: CharacterType.KANJI,
  },
  {
    characters: '調',
    meanings: ['investigate', 'tone'],
    onyomi: ['ちょう'],
    kunyomi: ['しら'],
    type: CharacterType.KANJI,
  },
  {
    characters: '鉄',
    meanings: ['iron'],
    onyomi: ['てつ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '葉',
    meanings: ['leaf', 'leaves'],
    onyomi: ['よう'],
    kunyomi: ['は', 'ば'],
    type: CharacterType.KANJI,
  },
  {
    characters: '習',
    meanings: ['learn'],
    onyomi: ['しゅう'],
    kunyomi: ['なら'],
    type: CharacterType.KANJI,
  },
  {
    characters: '軽',
    meanings: ['light', 'lightweight', 'light weight'],
    onyomi: ['けい'],
    kunyomi: ['かる', 'かろ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '最',
    meanings: ['most'],
    onyomi: ['さい'],
    kunyomi: ['もっと'],
    type: CharacterType.KANJI,
  },
  {
    characters: '開',
    meanings: ['open'],
    onyomi: ['かい'],
    kunyomi: ['あ', 'ひら'],
    type: CharacterType.KANJI,
  },
  {
    characters: '頁',
    meanings: ['page'],
    onyomi: ['けつ', 'よう'],
    kunyomi: ['ぺ-じ', 'かしら'],
    type: CharacterType.KANJI,
  },
  {
    characters: '求',
    meanings: ['request'],
    onyomi: ['きゅう'],
    kunyomi: ['もと'],
    type: CharacterType.KANJI,
  },
  {
    characters: '転',
    meanings: ['revolve'],
    onyomi: ['てん'],
    kunyomi: ['ころ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '路',
    meanings: ['road'],
    onyomi: ['ろ'],
    kunyomi: ['じ', 'みち'],
    type: CharacterType.KANJI,
  },
  {
    characters: '病',
    meanings: ['sick', 'sickness', 'ill', 'illness'],
    onyomi: ['びょう'],
    kunyomi: ['や', 'やまい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '横',
    meanings: ['side', 'horizontal'],
    onyomi: ['おう'],
    kunyomi: ['よこ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '起',
    meanings: ['wake up'],
    onyomi: ['き'],
    kunyomi: ['お'],
    type: CharacterType.KANJI,
  },
  {
    characters: '功',
    meanings: ['achievement', 'accomplishment'],
    onyomi: ['こう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '成',
    meanings: ['become'],
    onyomi: ['せい'],
    kunyomi: ['な'],
    type: CharacterType.KANJI,
  },
  {
    characters: '岸',
    meanings: ['coast', 'shore'],
    onyomi: ['がん'],
    kunyomi: ['きし'],
    type: CharacterType.KANJI,
  },
  {
    characters: '競',
    meanings: ['compete'],
    onyomi: ['きょう', 'けい'],
    kunyomi: ['きそ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '争',
    meanings: ['conflict'],
    onyomi: ['そう'],
    kunyomi: ['あらそ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '便',
    meanings: ['convenience', 'convenient'],
    onyomi: ['べん', 'びん'],
    kunyomi: ['たよ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '老',
    meanings: ['elderly'],
    onyomi: ['ろう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '命',
    meanings: ['fate', 'life'],
    onyomi: ['めい', 'みょう'],
    kunyomi: ['いのち'],
    type: CharacterType.KANJI,
  },
  {
    characters: '指',
    meanings: ['finger'],
    onyomi: ['し'],
    kunyomi: ['ゆび', 'さ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '初',
    meanings: ['first'],
    onyomi: ['しょ'],
    kunyomi: ['はじ', 'はつ', 'そ', 'ぞ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '味',
    meanings: ['flavor', 'taste'],
    onyomi: ['み'],
    kunyomi: ['あじ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '追',
    meanings: ['chase', 'follow'],
    onyomi: ['つい'],
    kunyomi: ['お'],
    type: CharacterType.KANJI,
  },
  {
    characters: '神',
    meanings: ['god'],
    onyomi: ['しん', 'じん'],
    kunyomi: ['かみ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '良',
    meanings: ['good'],
    onyomi: ['りょう'],
    kunyomi: ['よ', 'い'],
    type: CharacterType.KANJI,
  },
  {
    characters: '意',
    meanings: ['idea'],
    onyomi: ['い'],
    type: CharacterType.KANJI,
  },
  {
    characters: '労',
    meanings: ['labor'],
    onyomi: ['ろう'],
    kunyomi: ['いたわ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '級',
    meanings: ['level', 'grade', 'rank'],
    onyomi: ['きゅう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '好',
    meanings: ['like'],
    onyomi: ['こう'],
    kunyomi: ['す', 'この'],
    type: CharacterType.KANJI,
  },
  {
    characters: '昔',
    meanings: ['long time ago', 'long ago'],
    onyomi: ['せき', 'しゃく'],
    kunyomi: ['むかし'],
    type: CharacterType.KANJI,
  },
  {
    characters: '低',
    meanings: ['low'],
    onyomi: ['てい'],
    kunyomi: ['ひく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '育',
    meanings: ['nurture', 'raise'],
    onyomi: ['いく'],
    kunyomi: ['そだ', 'はぐく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '令',
    meanings: ['orders'],
    onyomi: ['れい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '拾',
    meanings: ['pick up'],
    onyomi: ['しゅう'],
    kunyomi: ['ひろ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '注',
    meanings: ['pour'],
    onyomi: ['ちゅう'],
    kunyomi: ['そそ', 'さ', 'つ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '利',
    meanings: ['profit', 'benefit', 'advantage'],
    onyomi: ['り'],
    kunyomi: ['き'],
    type: CharacterType.KANJI,
  },
  {
    characters: '位',
    meanings: ['rank'],
    onyomi: ['い'],
    kunyomi: ['くらい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '仲',
    meanings: ['relationship'],
    onyomi: ['ちゅう'],
    kunyomi: ['なか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '放',
    meanings: ['release'],
    onyomi: ['ほう'],
    kunyomi: ['はな', 'ほう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '秒',
    meanings: ['second'],
    onyomi: ['びょう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '別',
    meanings: ['separate'],
    onyomi: ['べつ'],
    kunyomi: ['わか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '特',
    meanings: ['special'],
    onyomi: ['とく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '共',
    meanings: ['together'],
    onyomi: ['きょう'],
    kunyomi: ['とも'],
    type: CharacterType.KANJI,
  },
  {
    characters: '努',
    meanings: ['toil'],
    onyomi: ['ど'],
    kunyomi: ['つと'],
    type: CharacterType.KANJI,
  },
  {
    characters: '伝',
    meanings: ['transmit', 'tell'],
    onyomi: ['でん'],
    kunyomi: ['つた', 'つて'],
    type: CharacterType.KANJI,
  },
  {
    characters: '戦',
    meanings: ['war', 'battle'],
    onyomi: ['せん'],
    kunyomi: ['たたか', 'いくさ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '波',
    meanings: ['wave'],
    onyomi: ['は'],
    kunyomi: ['なみ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '洋',
    meanings: ['western style', 'ocean'],
    onyomi: ['よう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '働',
    meanings: ['work'],
    onyomi: ['どう'],
    kunyomi: ['はたら'],
    type: CharacterType.KANJI,
  },
  {
    characters: '悪',
    meanings: ['bad', 'evil'],
    onyomi: ['あく', 'お'],
    kunyomi: ['わる'],
    type: CharacterType.KANJI,
  },
  {
    characters: '息',
    meanings: ['breath'],
    onyomi: ['そく'],
    kunyomi: ['いき'],
    type: CharacterType.KANJI,
  },
  {
    characters: '章',
    meanings: ['chapter'],
    onyomi: ['しょう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '登',
    meanings: ['climb'],
    onyomi: ['とう', 'と'],
    kunyomi: ['のぼ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '寒',
    meanings: ['cold'],
    onyomi: ['かん'],
    kunyomi: ['さむ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '深',
    meanings: ['deep'],
    onyomi: ['しん'],
    kunyomi: ['ふか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '倍',
    meanings: ['double', 'times', 'multiply'],
    onyomi: ['ばい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '勉',
    meanings: ['exertion', 'endeavour', 'strive'],
    onyomi: ['べん'],
    type: CharacterType.KANJI,
  },
  {
    characters: '消',
    meanings: ['extinguish', 'blow out'],
    onyomi: ['しょう'],
    kunyomi: ['き', 'け'],
    type: CharacterType.KANJI,
  },
  {
    characters: '祭',
    meanings: ['festival'],
    onyomi: ['さい'],
    kunyomi: ['まつり', 'まつ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '階',
    meanings: ['floor', 'story'],
    onyomi: ['かい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '庭',
    meanings: ['garden'],
    onyomi: ['てい'],
    kunyomi: ['にわ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '港',
    meanings: ['port', 'harbour', 'harbor'],
    onyomi: ['こう'],
    kunyomi: ['みなと'],
    type: CharacterType.KANJI,
  },
  {
    characters: '暑',
    meanings: ['hot', 'hot weather'],
    onyomi: ['しょ'],
    kunyomi: ['あつ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '湯',
    meanings: ['hot water'],
    onyomi: ['とう'],
    kunyomi: ['ゆ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '僕',
    meanings: ['i', 'me'],
    onyomi: ['ぼく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '島',
    meanings: ['island'],
    onyomi: ['とう'],
    kunyomi: ['しま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '童',
    meanings: ['juvenile'],
    onyomi: ['どう'],
    type: CharacterType.KANJI,
  },
  {
    characters: '員',
    meanings: ['member'],
    onyomi: ['いん'],
    type: CharacterType.KANJI,
  },
  {
    characters: '商',
    meanings: ['merchandise'],
    onyomi: ['しょう'],
    kunyomi: ['あきな'],
    type: CharacterType.KANJI,
  },
  {
    characters: '都',
    meanings: ['metropolis'],
    onyomi: ['と', 'つ'],
    kunyomi: ['みやこ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '動',
    meanings: ['move'],
    onyomi: ['どう'],
    kunyomi: ['うご'],
    type: CharacterType.KANJI,
  },
  {
    characters: '第',
    meanings: ['ordinal number prefix', 'ordinal prefix'],
    onyomi: ['だい'],
    type: CharacterType.KANJI,
  },
  {
    characters: '期',
    meanings: ['period of time', 'time period'],
    onyomi: ['き'],
    type: CharacterType.KANJI,
  },
  {
    characters: '植',
    meanings: ['plant'],
    onyomi: ['しょく'],
    kunyomi: ['う'],
    type: CharacterType.KANJI,
  },
  {
    characters: '根',
    meanings: ['root'],
    onyomi: ['こん'],
    kunyomi: ['ね'],
    type: CharacterType.KANJI,
  },
  {
    characters: '短',
    meanings: ['short'],
    onyomi: ['たん'],
    kunyomi: ['みじか'],
    type: CharacterType.KANJI,
  },
  {
    characters: '球',
    meanings: ['sphere', 'ball'],
    onyomi: ['きゅう'],
    kunyomi: ['たま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '泉',
    meanings: ['spring', 'fountain'],
    onyomi: ['せん'],
    kunyomi: ['いずみ'],
    type: CharacterType.KANJI,
  },
  {
    characters: '流',
    meanings: ['stream'],
    onyomi: ['りゅう', 'る'],
    kunyomi: ['なが'],
    type: CharacterType.KANJI,
  },
  {
    characters: '陽',
    meanings: ['sunshine', 'sunlight'],
    onyomi: ['よう'],
    kunyomi: ['ひ'],
    nanori: ['はる'],
    type: CharacterType.KANJI,
  },
  {
    characters: '歯',
    meanings: ['tooth', 'teeth'],
    onyomi: ['し'],
    kunyomi: ['は'],
    type: CharacterType.KANJI,
  },
  {
    characters: '族',
    meanings: ['family', 'tribe'],
    onyomi: ['ぞく'],
    type: CharacterType.KANJI,
  },
  {
    characters: '旅',
    meanings: ['trip', 'travel'],
    onyomi: ['りょ'],
    kunyomi: ['たび'],
    type: CharacterType.KANJI,
  },
  {
    characters: '待',
    meanings: ['wait'],
    onyomi: ['たい'],
    kunyomi: ['ま'],
    type: CharacterType.KANJI,
  },
  {
    characters: '温',
    meanings: ['warm'],
    onyomi: ['おん'],
    kunyomi: ['あたた'],
    type: CharacterType.KANJI,
  },
  {
    characters: '着',
    meanings: ['wear', 'arrive'],
    onyomi: ['ちゃく'],
    kunyomi: ['き', 'つ'],
    type: CharacterType.KANJI,
  },
];

export default KANJI;
