import CharacterType from '../common/enums/character-type.enum';
import Kanji from './models/kanji.model';

const KANJI: Kanji[] = [
  {
    id: 1,
    characters: '上',
    meanings: ['above', 'up', 'over'],
    onyomi: ['じょう'],
    kunyomi: ['うえ', 'あ', 'のぼ', 'うわ', 'かみ'],
    type: CharacterType.KANJI,
  },
  {
    id: 2,
    characters: '下',
    meanings: ['below', 'down', 'under', 'beneath'],
    onyomi: ['か', 'げ'],
    kunyomi: ['した', 'さ', 'くだ', 'お'],
    type: CharacterType.KANJI,
  },
  {
    id: 3,
    characters: '大',
    meanings: ['big', 'large'],
    onyomi: ['たい', 'だい'],
    kunyomi: ['おお'],
    nanori: ['ひろ'],
    type: CharacterType.KANJI,
  },
  {
    id: 4,
    characters: '工',
    meanings: ['construction', 'industry', 'artisan', 'work', 'craft'],
    onyomi: ['こう', 'く'],
    type: CharacterType.KANJI,
  },
  {
    id: 5,
    characters: '八',
    meanings: ['eight'],
    onyomi: ['はち'],
    kunyomi: ['や', 'よう'],
    type: CharacterType.KANJI,
  },
  {
    id: 6,
    characters: '入',
    meanings: ['enter'],
    onyomi: ['にゅう'],
    kunyomi: ['はい', 'い'],
    type: CharacterType.KANJI,
  },
  {
    id: 7,
    characters: '山',
    meanings: ['mountain'],
    onyomi: ['さん'],
    kunyomi: ['やま'],
    type: CharacterType.KANJI,
  },
  {
    id: 8,
    characters: '口',
    meanings: ['mouth'],
    onyomi: ['こう', 'く'],
    kunyomi: ['くち'],
    type: CharacterType.KANJI,
  },
  {
    id: 9,
    characters: '九',
    meanings: ['nine'],
    onyomi: ['く', 'きゅう'],
    kunyomi: ['ここの'],
    type: CharacterType.KANJI,
  },
  {
    id: 10,
    characters: '一',
    meanings: ['one'],
    onyomi: ['いち', 'いつ'],
    kunyomi: ['ひと'],
    nanori: ['かず'],
    type: CharacterType.KANJI,
  },
  {
    id: 11,
    characters: '人',
    meanings: ['person'],
    onyomi: ['にん', 'じん'],
    kunyomi: ['ひと', 'と'],
    type: CharacterType.KANJI,
  },
  {
    id: 12,
    characters: '力',
    meanings: ['power', 'strength'],
    onyomi: ['りょく', 'りき'],
    kunyomi: ['ちから'],
    type: CharacterType.KANJI,
  },
  {
    id: 13,
    characters: '川',
    meanings: ['river'],
    onyomi: ['せん'],
    kunyomi: ['かわ'],
    type: CharacterType.KANJI,
  },
  {
    id: 14,
    characters: '七',
    meanings: ['seven'],
    onyomi: ['しち'],
    kunyomi: ['なな', 'なの'],
    type: CharacterType.KANJI,
  },
  {
    id: 15,
    characters: '十',
    meanings: ['ten'],
    onyomi: ['じゅう'],
    kunyomi: ['とお'],
    type: CharacterType.KANJI,
  },
  {
    id: 16,
    characters: '三',
    meanings: ['three'],
    onyomi: ['さん'],
    kunyomi: ['み'],
    type: CharacterType.KANJI,
  },
  {
    id: 17,
    characters: '二',
    meanings: ['two'],
    onyomi: ['に'],
    kunyomi: ['ふた'],
    type: CharacterType.KANJI,
  },
  {
    id: 18,
    characters: '女',
    meanings: ['woman'],
    onyomi: ['じょ'],
    kunyomi: ['おんな', 'め'],
    type: CharacterType.KANJI,
  },
  {
    id: 19,
    characters: '又',
    meanings: ['again'],
    kunyomi: ['また'],
    type: CharacterType.KANJI,
  },
  {
    id: 20,
    characters: '玉',
    meanings: ['ball'],
    onyomi: ['ぎょく'],
    kunyomi: ['たま'],
    type: CharacterType.KANJI,
  },
  {
    id: 21,
    characters: '本',
    meanings: ['book', 'origin', 'real', 'main'],
    onyomi: ['ほん'],
    kunyomi: ['もと'],
    type: CharacterType.KANJI,
  },
  {
    id: 22,
    characters: '子',
    meanings: ['child', 'kid'],
    onyomi: ['し', 'す'],
    kunyomi: ['こ'],
    type: CharacterType.KANJI,
  },
  {
    id: 23,
    characters: '丸',
    meanings: ['circle', 'circular', 'round'],
    onyomi: ['がん'],
    kunyomi: ['まる'],
    type: CharacterType.KANJI,
  },
  {
    id: 24,
    characters: '正',
    meanings: ['correct'],
    onyomi: ['せい', 'しょう'],
    kunyomi: ['ただ', 'まさ'],
    type: CharacterType.KANJI,
  },
  {
    id: 25,
    characters: '土',
    meanings: ['dirt', 'soil', 'earth', 'ground'],
    onyomi: ['ど', 'と'],
    kunyomi: ['つち'],
    type: CharacterType.KANJI,
  },
  {
    id: 26,
    characters: '犬',
    meanings: ['dog'],
    onyomi: ['けん'],
    kunyomi: ['いぬ'],
    type: CharacterType.KANJI,
  },
  {
    id: 27,
    characters: '夕',
    meanings: ['evening'],
    onyomi: ['せき'],
    kunyomi: ['ゆう'],
    type: CharacterType.KANJI,
  },
  {
    id: 28,
    characters: '出',
    meanings: ['exit'],
    onyomi: ['しゅつ'],
    kunyomi: ['で', 'だ'],
    type: CharacterType.KANJI,
  },
  {
    id: 29,
    characters: '目',
    meanings: ['eye'],
    onyomi: ['もく'],
    kunyomi: ['め'],
    type: CharacterType.KANJI,
  },
  {
    id: 30,
    characters: '了',
    meanings: ['finish', 'complete', 'end'],
    onyomi: ['りょう'],
    type: CharacterType.KANJI,
  },
  {
    id: 31,
    characters: '火',
    meanings: ['fire'],
    onyomi: ['か'],
    kunyomi: ['ひ', 'ほ'],
    type: CharacterType.KANJI,
  },
  {
    id: 32,
    characters: '五',
    meanings: ['five'],
    onyomi: ['ご'],
    kunyomi: ['いつ'],
    type: CharacterType.KANJI,
  },
  {
    id: 33,
    characters: '四',
    meanings: ['four'],
    onyomi: ['し'],
    kunyomi: ['よん', 'よ'],
    type: CharacterType.KANJI,
  },
  {
    id: 34,
    characters: '才',
    meanings: ['genius', 'wit', 'talent', 'ability'],
    onyomi: ['さい'],
    type: CharacterType.KANJI,
  },
  {
    id: 35,
    characters: '手',
    meanings: ['hand'],
    onyomi: ['しゅ', 'ず'],
    kunyomi: ['て'],
    type: CharacterType.KANJI,
  },
  {
    id: 36,
    characters: '天',
    meanings: ['heaven'],
    onyomi: ['てん'],
    kunyomi: ['あま'],
    type: CharacterType.KANJI,
  },
  {
    id: 37,
    characters: '王',
    meanings: ['king'],
    onyomi: ['おう'],
    type: CharacterType.KANJI,
  },
  {
    id: 38,
    characters: '左',
    meanings: ['left'],
    onyomi: ['さ'],
    kunyomi: ['ひだり'],
    type: CharacterType.KANJI,
  },
  {
    id: 39,
    characters: '中',
    meanings: ['middle', 'in', 'inside', 'center'],
    onyomi: ['ちゅう'],
    kunyomi: ['なか'],
    type: CharacterType.KANJI,
  },
  {
    id: 40,
    characters: '月',
    meanings: ['moon', 'month'],
    onyomi: ['げつ', 'がつ'],
    kunyomi: ['つき'],
    type: CharacterType.KANJI,
  },
  {
    id: 41,
    characters: '々',
    meanings: ['repeater', 'repetition', 'reduplication', 'iteration mark'],
    kunyomi: ['のま'],
    type: CharacterType.KANJI,
  },
  {
    id: 42,
    characters: '田',
    meanings: ['rice paddy', 'rice field', 'field'],
    onyomi: ['でん'],
    kunyomi: ['た'],
    type: CharacterType.KANJI,
  },
  {
    id: 43,
    characters: '右',
    meanings: ['right'],
    onyomi: ['ゆう', 'う'],
    kunyomi: ['みぎ'],
    type: CharacterType.KANJI,
  },
  {
    id: 44,
    characters: '六',
    meanings: ['six'],
    onyomi: ['ろく'],
    kunyomi: ['む'],
    type: CharacterType.KANJI,
  },
  {
    id: 45,
    characters: '小',
    meanings: ['small', 'little'],
    onyomi: ['しょう'],
    kunyomi: ['ちい', 'こ', 'お'],
    type: CharacterType.KANJI,
  },
  {
    id: 46,
    characters: '立',
    meanings: ['stand'],
    onyomi: ['りつ', 'りゅう'],
    kunyomi: ['た'],
    type: CharacterType.KANJI,
  },
  {
    id: 47,
    characters: '丁',
    meanings: ['street'],
    onyomi: ['ちょう', 'てい'],
    type: CharacterType.KANJI,
  },
  {
    id: 48,
    characters: '日',
    meanings: ['sun', 'day'],
    onyomi: ['にち', 'じつ'],
    kunyomi: ['ひ', 'か', 'び'],
    type: CharacterType.KANJI,
  },
  {
    id: 49,
    characters: '刀',
    meanings: ['sword', 'katana'],
    onyomi: ['とう'],
    kunyomi: ['かたな'],
    type: CharacterType.KANJI,
  },
  {
    id: 50,
    characters: '千',
    meanings: ['thousand'],
    onyomi: ['せん'],
    kunyomi: ['ち'],
    type: CharacterType.KANJI,
  },
  {
    id: 51,
    characters: '木',
    meanings: ['tree', 'wood'],
    onyomi: ['もく', 'ぼく'],
    kunyomi: ['き', 'こ'],
    type: CharacterType.KANJI,
  },
  {
    id: 52,
    characters: '水',
    meanings: ['water'],
    onyomi: ['すい'],
    kunyomi: ['みず'],
    type: CharacterType.KANJI,
  },
  {
    id: 53,
    characters: '白',
    meanings: ['white'],
    onyomi: ['はく'],
    kunyomi: ['しろ', 'しら'],
    type: CharacterType.KANJI,
  },
  {
    id: 54,
    characters: '文',
    meanings: ['writing', 'sentence'],
    onyomi: ['ぶん', 'もん'],
    kunyomi: ['ふみ'],
    type: CharacterType.KANJI,
  },
  {
    id: 55,
    characters: '円',
    meanings: ['yen', 'round', 'circle'],
    onyomi: ['えん'],
    kunyomi: ['まる'],
    type: CharacterType.KANJI,
  },
  {
    id: 56,
    characters: '矢',
    meanings: ['arrow'],
    onyomi: ['し'],
    kunyomi: ['や'],
    type: CharacterType.KANJI,
  },
  {
    id: 57,
    characters: '市',
    meanings: ['city'],
    onyomi: ['し'],
    kunyomi: ['いち'],
    type: CharacterType.KANJI,
  },
  {
    id: 58,
    characters: '牛',
    meanings: ['cow'],
    onyomi: ['ぎゅう'],
    kunyomi: ['うし'],
    type: CharacterType.KANJI,
  },
  {
    id: 59,
    characters: '切',
    meanings: ['cut'],
    onyomi: ['せつ'],
    kunyomi: ['き'],
    type: CharacterType.KANJI,
  },
  {
    id: 60,
    characters: '方',
    meanings: ['direction', 'way'],
    onyomi: ['ほう'],
    kunyomi: ['かた'],
    type: CharacterType.KANJI,
  },
  {
    id: 61,
    characters: '戸',
    meanings: ['door'],
    onyomi: ['こ'],
    kunyomi: ['と'],
    type: CharacterType.KANJI,
  },
  {
    id: 62,
    characters: '太',
    meanings: ['fat'],
    onyomi: ['たい', 'た'],
    kunyomi: ['ふと'],
    nanori: ['おお'],
    type: CharacterType.KANJI,
  },
  {
    id: 63,
    characters: '父',
    meanings: ['father', 'dad'],
    onyomi: ['ふ'],
    kunyomi: ['ちち', 'とう'],
    type: CharacterType.KANJI,
  },
  {
    id: 64,
    characters: '少',
    meanings: ['few', 'a little'],
    onyomi: ['しょう'],
    kunyomi: ['すこ', 'すく'],
    type: CharacterType.KANJI,
  },
  {
    id: 65,
    characters: '友',
    meanings: ['friend'],
    onyomi: ['ゆう'],
    kunyomi: ['とも'],
    type: CharacterType.KANJI,
  },
  {
    id: 66,
    characters: '毛',
    meanings: ['fur', 'hair'],
    onyomi: ['もう'],
    kunyomi: ['け'],
    type: CharacterType.KANJI,
  },
  {
    id: 67,
    characters: '半',
    meanings: ['half'],
    onyomi: ['はん'],
    kunyomi: ['なか'],
    type: CharacterType.KANJI,
  },
  {
    id: 68,
    characters: '心',
    meanings: ['heart'],
    onyomi: ['しん'],
    kunyomi: ['こころ'],
    type: CharacterType.KANJI,
  },
  {
    id: 69,
    characters: '内',
    meanings: ['inside', 'within'],
    onyomi: ['ない'],
    kunyomi: ['うち'],
    type: CharacterType.KANJI,
  },
  {
    id: 70,
    characters: '生',
    meanings: ['life'],
    onyomi: ['せい', 'しょう'],
    kunyomi: ['い', 'なま', 'う', 'は', 'き'],
    type: CharacterType.KANJI,
  },
  {
    id: 71,
    characters: '台',
    meanings: ['machine'],
    onyomi: ['だい', 'たい'],
    type: CharacterType.KANJI,
  },
  {
    id: 72,
    characters: '母',
    meanings: ['mother', 'mom'],
    onyomi: ['ぼ'],
    kunyomi: ['はは', 'かあ'],
    type: CharacterType.KANJI,
  },
  {
    id: 73,
    characters: '午',
    meanings: ['noon'],
    onyomi: ['ご'],
    type: CharacterType.KANJI,
  },
  {
    id: 74,
    characters: '北',
    meanings: ['north'],
    onyomi: ['ほく'],
    kunyomi: ['きた'],
    type: CharacterType.KANJI,
  },
  {
    id: 75,
    characters: '今',
    meanings: ['now', 'immediately'],
    onyomi: ['こん', 'きん'],
    kunyomi: ['いま'],
    type: CharacterType.KANJI,
  },
  {
    id: 76,
    characters: '古',
    meanings: ['old'],
    onyomi: ['こ'],
    kunyomi: ['ふる'],
    type: CharacterType.KANJI,
  },
  {
    id: 77,
    characters: '元',
    meanings: ['origin'],
    onyomi: ['げん', 'がん'],
    kunyomi: ['もと'],
    type: CharacterType.KANJI,
  },
  {
    id: 78,
    characters: '外',
    meanings: ['outside'],
    onyomi: ['がい'],
    kunyomi: ['そと', 'はず'],
    type: CharacterType.KANJI,
  },
  {
    id: 79,
    characters: '分',
    meanings: ['part'],
    onyomi: ['ぶん', 'ふん', 'ぶ'],
    kunyomi: ['わ'],
    type: CharacterType.KANJI,
  },
  {
    id: 80,
    characters: '公',
    meanings: ['public'],
    onyomi: ['こう'],
    type: CharacterType.KANJI,
  },
  {
    id: 81,
    characters: '引',
    meanings: ['pull'],
    onyomi: ['いん'],
    kunyomi: ['ひ'],
    type: CharacterType.KANJI,
  },
  {
    id: 82,
    characters: '止',
    meanings: ['stop'],
    onyomi: ['し'],
    kunyomi: ['と', 'や'],
    type: CharacterType.KANJI,
  },
  {
    id: 83,
    characters: '用',
    meanings: ['task', 'use'],
    onyomi: ['よう'],
    kunyomi: ['もち'],
    type: CharacterType.KANJI,
  },
  {
    id: 84,
    characters: '万',
    meanings: ['ten thousand'],
    onyomi: ['まん', 'ばん'],
    type: CharacterType.KANJI,
  },
  {
    id: 85,
    characters: '広',
    meanings: ['wide', 'broad', 'spread'],
    onyomi: ['こう'],
    kunyomi: ['ひろ'],
    type: CharacterType.KANJI,
  },
  {
    id: 86,
    characters: '冬',
    meanings: ['winter'],
    onyomi: ['とう'],
    kunyomi: ['ふゆ'],
    type: CharacterType.KANJI,
  },
  {
    id: 87,
    characters: '百',
    meanings: ['hundred'],
    onyomi: ['ひゃく'],
    kunyomi: ['もも'],
    type: CharacterType.KANJI,
  },
  {
    id: 88,
    characters: '金',
    meanings: ['gold'],
    onyomi: ['きん'],
    kunyomi: ['かね'],
    type: CharacterType.KANJI,
  },
  {
    id: 89,
    characters: '休',
    meanings: ['rest'],
    onyomi: ['きゅう'],
    kunyomi: ['やす'],
    type: CharacterType.KANJI,
  },
  {
    id: 90,
    characters: '耳',
    meanings: ['ear', 'ears'],
    onyomi: ['じ'],
    kunyomi: ['みみ'],
    type: CharacterType.KANJI,
  },
  {
    id: 91,
    characters: '足',
    meanings: ['foot', 'leg', 'sufficient'],
    onyomi: ['そく'],
    kunyomi: ['あし', 'た'],
    type: CharacterType.KANJI,
  },
  {
    id: 92,
    characters: '男',
    meanings: ['man', 'boy'],
    onyomi: ['だん', 'なん'],
    kunyomi: ['おとこ'],
    type: CharacterType.KANJI,
  },
  {
    id: 93,
    characters: '空',
    meanings: ['sky', 'empty'],
    onyomi: ['くう'],
    kunyomi: ['そら', 'あ', 'から', 'す'],
    type: CharacterType.KANJI,
  },
  {
    id: 94,
    characters: '気',
    meanings: ['energy', 'spirit'],
    onyomi: ['き', 'け'],
    kunyomi: ['いき'],
    type: CharacterType.KANJI,
  },
  {
    id: 95,
    characters: '見',
    meanings: ['see'],
    onyomi: ['けん'],
    kunyomi: ['み'],
    type: CharacterType.KANJI,
  },
  {
    id: 96,
    characters: '雨',
    meanings: ['rain'],
    onyomi: ['う'],
    kunyomi: ['あめ', 'あま'],
    type: CharacterType.KANJI,
  },
  {
    id: 97,
    characters: '林',
    meanings: ['forest', 'grove'],
    onyomi: ['りん'],
    kunyomi: ['はやし'],
    type: CharacterType.KANJI,
  },
  {
    id: 98,
    characters: '森',
    meanings: ['forest', 'woods'],
    onyomi: ['しん'],
    kunyomi: ['もり'],
    type: CharacterType.KANJI,
  },
  {
    id: 99,
    characters: '石',
    meanings: ['stone'],
    onyomi: ['せき'],
    kunyomi: ['いし', 'こく', 'しゃく'],
    type: CharacterType.KANJI,
  },
  {
    id: 100,
    characters: '花',
    meanings: ['flower'],
    onyomi: ['か', 'け'],
    kunyomi: ['はな'],
    type: CharacterType.KANJI,
  },
  {
    id: 101,
    characters: '虫',
    meanings: ['insect', 'bug'],
    onyomi: ['ちゅう', 'き'],
    kunyomi: ['むし'],
    type: CharacterType.KANJI,
  },
  {
    id: 102,
    characters: '町',
    meanings: ['town'],
    onyomi: ['ちょう'],
    kunyomi: ['まち'],
    type: CharacterType.KANJI,
  },
  {
    id: 103,
    characters: '村',
    meanings: ['village'],
    onyomi: ['そん'],
    kunyomi: ['むら'],
    type: CharacterType.KANJI,
  },
  {
    id: 104,
    characters: '赤',
    meanings: ['red'],
    onyomi: ['せき'],
    kunyomi: ['あか'],
    type: CharacterType.KANJI,
  },
  {
    id: 105,
    characters: '青',
    meanings: ['blue'],
    onyomi: ['せい', 'しょう'],
    kunyomi: ['あお'],
    type: CharacterType.KANJI,
  },
  {
    id: 106,
    characters: '先',
    meanings: ['previous', 'ahead', 'past', 'former'],
    onyomi: ['せん'],
    kunyomi: ['さき', 'まず'],
    type: CharacterType.KANJI,
  },
  {
    id: 107,
    characters: '早',
    meanings: ['early', 'fast', 'quick'],
    onyomi: ['そう'],
    kunyomi: ['はや', 'さ'],
    type: CharacterType.KANJI,
  },
  {
    id: 107,
    characters: '名',
    meanings: ['name', 'famous'],
    onyomi: ['めい', 'みょう'],
    kunyomi: ['な'],
    type: CharacterType.KANJI,
  },
  {
    id: 108,
    characters: '校',
    meanings: ['school'],
    onyomi: ['こう'],
    type: CharacterType.KANJI,
  },
  {
    id: 109,
    characters: '字',
    meanings: ['letter', 'character', 'symbol'],
    onyomi: ['じ'],
    kunyomi: ['あざ'],
    type: CharacterType.KANJI,
  },
  {
    id: 110,
    characters: '学',
    meanings: ['study', 'learn', 'learning'],
    onyomi: ['がく'],
    kunyomi: ['まな'],
    type: CharacterType.KANJI,
  },
  {
    id: 111,
    characters: '年',
    meanings: ['year'],
    onyomi: ['ねん'],
    kunyomi: ['とし'],
    type: CharacterType.KANJI,
  },
  {
    id: 112,
    characters: '音',
    meanings: ['sound'],
    onyomi: ['おん', 'いん'],
    kunyomi: ['おと', 'ね'],
    type: CharacterType.KANJI,
  },
  {
    id: 113,
    characters: '糸',
    meanings: ['thread'],
    onyomi: ['し'],
    kunyomi: ['いと'],
    type: CharacterType.KANJI,
  },
  {
    id: 114,
    characters: '車',
    meanings: ['car'],
    onyomi: ['しゃ'],
    kunyomi: ['くるま'],
    type: CharacterType.KANJI,
  },
  {
    id: 115,
    characters: '貝',
    meanings: ['shellfish', 'shell'],
    kunyomi: ['かい'],
    type: CharacterType.KANJI,
  },
  {
    id: 116,
    characters: '草',
    meanings: ['grass', 'weed'],
    onyomi: ['そう'],
    kunyomi: ['くさ'],
    type: CharacterType.KANJI,
  },
  {
    id: 117,
    characters: '竹',
    meanings: ['bamboo'],
    kunyomi: ['たけ'],
    type: CharacterType.KANJI,
  },
  {
    id: 118,
    characters: '雲',
    meanings: ['cloud'],
    onyomi: ['うん'],
    kunyomi: ['くも'],
    type: CharacterType.KANJI,
  },
  {
    id: 119,
    characters: '何',
    meanings: ['what'],
    onyomi: ['か'],
    kunyomi: ['なに', 'なん'],
    type: CharacterType.KANJI,
  },
  {
    id: 120,
    characters: '科',
    meanings: ['course', 'science', 'department'],
    onyomi: ['か'],
    type: CharacterType.KANJI,
  },
  {
    id: 121,
    characters: '遠',
    meanings: ['far'],
    onyomi: ['えん'],
    kunyomi: ['とお'],
    type: CharacterType.KANJI,
  },
  {
    id: 122,
    characters: '夏',
    meanings: ['summer'],
    onyomi: ['げ', 'か', 'が'],
    kunyomi: ['なつ'],
    type: CharacterType.KANJI,
  },
  {
    id: 123,
    characters: '家',
    meanings: ['house', 'home'],
    onyomi: ['か', 'け'],
    kunyomi: ['いえ', 'や', 'うち'],
    type: CharacterType.KANJI,
  },
  {
    id: 124,
    characters: '歌',
    meanings: ['song', 'sing'],
    onyomi: ['か'],
    kunyomi: ['うた'],
    type: CharacterType.KANJI,
  },
  {
    id: 125,
    characters: '画',
    meanings: ['drawing', 'picture', 'painting'],
    onyomi: ['が', 'かく'],
    type: CharacterType.KANJI,
  },
  {
    id: 126,
    characters: '会',
    meanings: ['meet'],
    onyomi: ['かい'],
    kunyomi: ['あ', 'え'],
    type: CharacterType.KANJI,
  },
  {
    id: 127,
    characters: '海',
    meanings: ['sea', 'ocean'],
    onyomi: ['かい'],
    kunyomi: ['うみ'],
    type: CharacterType.KANJI,
  },
  {
    id: 128,
    characters: '回',
    meanings: ['times', 'revolve', 'turn', 'go around'],
    onyomi: ['かい'],
    kunyomi: ['まわ'],
    type: CharacterType.KANJI,
  },
  {
    id: 129,
    characters: '絵',
    meanings: ['drawing', 'picture', 'painting'],
    onyomi: ['かい', 'え'],
    type: CharacterType.KANJI,
  },
  {
    id: 130,
    characters: '園',
    meanings: ['garden', 'park'],
    onyomi: ['えん'],
    kunyomi: ['その'],
    type: CharacterType.KANJI,
  },
  {
    id: 131,
    characters: '間',
    meanings: ['interval', 'space'],
    onyomi: ['かん', 'けん'],
    kunyomi: ['あいだ', 'ま'],
    type: CharacterType.KANJI,
  },
  {
    id: 132,
    characters: '顔',
    meanings: ['face'],
    onyomi: ['がん'],
    kunyomi: ['かお'],
    type: CharacterType.KANJI,
  },
  {
    id: 133,
    characters: '汽',
    meanings: ['steam'],
    onyomi: ['き'],
    type: CharacterType.KANJI,
  },
  {
    id: 134,
    characters: '記',
    meanings: ['write down', 'record', 'chronicle'],
    onyomi: ['き'],
    kunyomi: ['しる'],
    type: CharacterType.KANJI,
  },
  {
    id: 135,
    characters: '帰',
    meanings: ['return', 'return home'],
    onyomi: ['き'],
    kunyomi: ['かえ'],
    type: CharacterType.KANJI,
  },
  {
    id: 136,
    characters: '魚',
    meanings: ['fish'],
    onyomi: ['ぎょ'],
    kunyomi: ['うお', 'さかな'],
    type: CharacterType.KANJI,
  },
  {
    id: 137,
    characters: '京',
    meanings: ['capital'],
    onyomi: ['きょう', 'けい'],
    kunyomi: ['みやこ'],
    type: CharacterType.KANJI,
  },
  {
    id: 138,
    characters: '教',
    meanings: ['teach'],
    onyomi: ['きょう'],
    kunyomi: ['おし', 'おそ'],
    type: CharacterType.KANJI,
  },
  {
    id: 139,
    characters: '強',
    meanings: ['strong', 'strength', 'strengthen'],
    onyomi: ['きょう', 'ごう'],
    kunyomi: ['つよ', 'し'],
    type: CharacterType.KANJI,
  },
  {
    id: 140,
    characters: '角',
    meanings: ['angle', 'corner', 'antler'],
    onyomi: ['かく'],
    kunyomi: ['かど', 'つの'],
    type: CharacterType.KANJI,
  },
  {
    id: 141,
    characters: '近',
    meanings: ['near', 'close'],
    onyomi: ['きん', 'こん'],
    kunyomi: ['ちか'],
    type: CharacterType.KANJI,
  },
  {
    id: 142,
    characters: '形',
    meanings: ['shape', 'form', 'appearance'],
    onyomi: ['けい', 'ぎょう'],
    kunyomi: ['かた', 'かたち'],
    type: CharacterType.KANJI,
  },
  {
    id: 143,
    characters: '計',
    meanings: ['measure', 'measurement', 'plan'],
    onyomi: ['けい'],
    kunyomi: ['はか'],
    type: CharacterType.KANJI,
  },
  {
    id: 144,
    characters: '語',
    meanings: ['language', 'speak', 'word'],
    onyomi: ['ご'],
    kunyomi: ['かた'],
    type: CharacterType.KANJI,
  },
  {
    id: 145,
    characters: '原',
    meanings: ['original', 'fundamental', 'field'],
    onyomi: ['げん'],
    kunyomi: ['はら'],
    type: CharacterType.KANJI,
  },
  {
    id: 146,
    characters: '後',
    meanings: ['after', 'behind', 'back', 'later'],
    onyomi: ['ご', 'こう'],
    kunyomi: ['のち', 'うし', 'あと', 'おく'],
    type: CharacterType.KANJI,
  },
  {
    id: 147,
    characters: '交',
    meanings: ['mix', 'mingle', 'exchange', 'intercourse'],
    onyomi: ['こう'],
    kunyomi: ['まじ', 'ま', 'か'],
    type: CharacterType.KANJI,
  },
  {
    id: 148,
    characters: '光',
    meanings: ['sunlight', 'light', 'shine', 'brilliance'],
    onyomi: ['こう'],
    kunyomi: ['ひかり', 'ひか'],
    type: CharacterType.KANJI,
  },
  {
    id: 149,
    characters: '行',
    meanings: ['go', 'do', 'conduct', 'stroke'],
    onyomi: ['こう', 'ぎょう'],
    kunyomi: ['い', 'ゆ', 'おこな'],
    type: CharacterType.KANJI,
  },
  {
    id: 150,
    characters: '考',
    meanings: ['think', 'consider'],
    onyomi: ['こう'],
    kunyomi: ['かんが'],
    type: CharacterType.KANJI,
  },
  {
    id: 151,
    characters: '高',
    meanings: ['tall', 'expensive', 'high'],
    onyomi: ['こう'],
    kunyomi: ['たか'],
    type: CharacterType.KANJI,
  },
  {
    id: 152,
    characters: '黄',
    meanings: ['yellow'],
    onyomi: ['こう', 'おう'],
    kunyomi: ['き', 'こ'],
    type: CharacterType.KANJI,
  },
  {
    id: 153,
    characters: '合',
    meanings: ['combine', 'join', 'union', 'fit', 'suit'],
    onyomi: ['ごう', 'がっ', 'かっ'],
    kunyomi: ['あ', 'あい'],
    type: CharacterType.KANJI,
  },
  {
    id: 154,
    characters: '谷',
    meanings: ['valley'],
    onyomi: ['こく'],
    kunyomi: ['たに'],
    nanori: ['せ'],
    type: CharacterType.KANJI,
  },
  {
    id: 155,
    characters: '国',
    meanings: ['country', 'nation'],
    onyomi: ['こく'],
    kunyomi: ['くに'],
    type: CharacterType.KANJI,
  },
  {
    id: 156,
    characters: '黒',
    meanings: ['black'],
    onyomi: ['こく'],
    kunyomi: ['くろ'],
    type: CharacterType.KANJI,
  },
  {
    id: 157,
    characters: '作',
    meanings: ['make', 'work'],
    onyomi: ['さく', 'さ'],
    kunyomi: ['つく'],
    type: CharacterType.KANJI,
  },
  {
    id: 158,
    characters: '算',
    meanings: ['calculate', 'count'],
    onyomi: ['さん'],
    kunyomi: ['そろ'],
    type: CharacterType.KANJI,
  },
  {
    id: 159,
    characters: '自',
    meanings: ['oneself', 'self'],
    onyomi: ['じ', 'し'],
    kunyomi: ['みずか'],
    type: CharacterType.KANJI,
  },
  {
    id: 160,
    characters: '寺',
    meanings: ['temple'],
    onyomi: ['じ'],
    kunyomi: ['てら'],
    type: CharacterType.KANJI,
  },
  {
    id: 161,
    characters: '時',
    meanings: ['time', "o'clock", 'hour', 'occasion'],
    onyomi: ['じ'],
    kunyomi: ['とき'],
    type: CharacterType.KANJI,
  },
  {
    id: 162,
    characters: '思',
    meanings: ['think', 'thought'],
    onyomi: ['し'],
    kunyomi: ['おも'],
    type: CharacterType.KANJI,
  },
  {
    id: 163,
    characters: '紙',
    meanings: ['paper'],
    onyomi: ['し'],
    kunyomi: ['かみ'],
    type: CharacterType.KANJI,
  },
  {
    id: 164,
    characters: '室',
    meanings: ['room'],
    onyomi: ['しつ'],
    kunyomi: ['むろ'],
    type: CharacterType.KANJI,
  },
];

export default KANJI;
